<?php
/**
 * Plugin Name: Frak
 * Plugin URI: https://docs.frak.id/components/frak-setup
 * Description: Adds Frak configuration to your WordPress site. Requires a block theme.
 * Version: 1.0.0
 * Requires at least: 6.4
 * Requires PHP: 8.0
 * Author: Frak-Labs
 * Author URI: https://frak.id
 * License: GPL-3.0-only
 * License URI: https://www.gnu.org/licenses/gpl-3.0.html
 * Text Domain: frak
 * Domain Path: /languages
 *
 * @package Frak_Integration
 */

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Define plugin constants.
define( 'FRAK_PLUGIN_FILE', __FILE__ );
define( 'FRAK_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'FRAK_PLUGIN_URL', plugin_dir_url( __FILE__ ) );
define( 'FRAK_PLUGIN_VERSION', '1.0.0' );

// Composer's classmap autoloader covers every `Frak_*` class under `includes/`
// and `admin/`. The classmap is regenerated by `composer install --optimize-autoloader`
// (see `build.sh`), so production zips always ship a warm autoloader — no SPL
// closures fire per request.
//
// When the vendor folder is missing (developer checkout unzipped instead of
// the packaged `dist/*.zip`, or a composer install that bailed out) we surface
// an explicit admin notice rather than silently no-op'ing — previously the
// plugin activated but every class-lookup would fatally error on first hit.
if ( ! file_exists( FRAK_PLUGIN_DIR . 'vendor/autoload.php' ) ) {
	add_action(
		'admin_notices',
		static function () {
			echo '<div class="notice notice-error"><p>';
			echo esc_html__( 'Frak plugin is missing its vendor/ folder. Install the packaged .zip from dist/, or run `composer install` from the plugin directory.', 'frak' );
			echo '</p></div>';
		}
	);
	return;
}

require_once FRAK_PLUGIN_DIR . 'vendor/autoload.php';

/**
 * Load translations from the `languages/` directory. Called on `init` (which
 * is after `plugins_loaded`, matching the modern WP guidance for hooking
 * i18n loading). Self-hosted installs need this explicit call — WP.org
 * auto-loading from translate.wordpress.org only fires for plugins listed in
 * the directory, which this one is not yet.
 */
add_action(
	'init',
	static function () {
		load_plugin_textdomain( 'frak', false, dirname( plugin_basename( FRAK_PLUGIN_FILE ) ) . '/languages' );
	}
);

/**
 * Bootstrap the plugin's static controller. {@see Frak_Plugin::boot()}
 * registers the rest of the hooks on `init` so class availability is
 * guaranteed (Composer autoload is wired up above).
 */
add_action( 'plugins_loaded', array( 'Frak_Plugin', 'boot' ) );

/**
 * Run the settings migration on plugin activation — one-time bootstrap
 * for fresh installs and explicit reactivations.
 *
 * Also ensures the WooCommerce webhook exists when both a merchant and a
 * secret are already configured (reactivation after a deactivate/activate
 * cycle, or install on a site that restored its `frak_*` options from a
 * backup). Ensure() itself is a no-op when prerequisites are missing, so
 * fresh installs still do the right thing — it just wires up later when
 * the admin saves the settings form.
 *
 * Bails with `wp_die()` when the vendor folder is absent so the operator
 * gets an actionable error instead of a partially-activated plugin.
 */
register_activation_hook(
	FRAK_PLUGIN_FILE,
	static function () {
		if ( ! file_exists( FRAK_PLUGIN_DIR . 'vendor/autoload.php' ) ) {
			wp_die(
				esc_html__( 'Frak plugin is missing its vendor/ folder. Install the packaged .zip from dist/, or run `composer install` from the plugin directory.', 'frak' ),
				esc_html__( 'Plugin activation failed', 'frak' ),
				array( 'back_link' => true )
			);
		}
		Frak_Settings::migrate();
		if ( class_exists( 'Frak_WC_Webhook_Registrar' ) ) {
			Frak_WC_Webhook_Registrar::ensure();
		}
		flush_rewrite_rules();
	}
);

/**
 * Remove the WooCommerce webhook we own on deactivation so the merchant's
 * WC admin UI doesn't accumulate stale rows. The settings themselves are
 * preserved (they live in `wp_options`) so a subsequent reactivation picks
 * up where we left off.
 */
register_deactivation_hook(
	FRAK_PLUGIN_FILE,
	static function () {
		if ( class_exists( 'Frak_WC_Webhook_Registrar' ) ) {
			Frak_WC_Webhook_Registrar::remove();
		}
	}
);

/**
 * Run the settings migration after the plugin is updated via the WordPress
 * updater — `register_activation_hook` does not fire on in-place upgrades,
 * so this covers the "bump CURRENT_VERSION, ship a new migration step" case.
 *
 * @param WP_Upgrader $upgrader Unused (required by signature).
 * @param array       $options  Hook payload describing the upgrade batch.
 */
add_action(
	'upgrader_process_complete',
	static function ( $upgrader, $options ) {
		unset( $upgrader );
		if ( ! isset( $options['action'], $options['type'], $options['plugins'] ) ) {
			return;
		}
		if ( 'update' !== $options['action'] || 'plugin' !== $options['type'] ) {
			return;
		}
		if ( ! is_array( $options['plugins'] ) ) {
			return;
		}
		if ( ! in_array( plugin_basename( FRAK_PLUGIN_FILE ), $options['plugins'], true ) ) {
			return;
		}
		Frak_Settings::migrate();
	},
	10,
	2
);

/**
 * Declare compatibility with WooCommerce High-Performance Order Storage (HPOS / custom order tables).
 */
add_action(
	'before_woocommerce_init',
	static function () {
		if ( class_exists( \Automattic\WooCommerce\Utilities\FeaturesUtil::class ) ) {
			\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility( 'custom_order_tables', FRAK_PLUGIN_FILE, true );
		}
	}
);
