<?php
/**
 * Plugin Name: Frak
 * Plugin URI: https://docs.frak.id/components/frak-setup
 * Description: Adds Frak configuration to your WordPress site. Requires a block theme.
 * Version: 1.0.0
 * Requires at least: 6.4
 * Requires PHP: 8.3
 * Author: Frak-Labs
 * Author URI: https://frak.id
 * License: GPL-3.0-only
 * License URI: https://www.gnu.org/licenses/gpl-3.0.html
 * Text Domain: frak
 * Domain Path: /languages
 *
 * @package Frak_Integration
 */

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Define plugin constants.
define( 'FRAK_PLUGIN_FILE', __FILE__ );
define( 'FRAK_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'FRAK_PLUGIN_URL', plugin_dir_url( __FILE__ ) );
define( 'FRAK_PLUGIN_VERSION', '1.0.0' );

// Composer's classmap autoloader covers every `Frak_*` class under `includes/`
// and `admin/`. The classmap is regenerated by `composer install --optimize-autoloader`
// (see `build.sh`), so production zips always ship a warm autoloader — no SPL
// closures fire per request.
if ( file_exists( FRAK_PLUGIN_DIR . 'vendor/autoload.php' ) ) {
	require_once FRAK_PLUGIN_DIR . 'vendor/autoload.php';
}

/**
 * Initialize the plugin.
 */
function frak_init() {
	Frak_Plugin::instance();
}
add_action( 'plugins_loaded', 'frak_init' );

/**
 * Run the settings migration on plugin activation — one-time bootstrap
 * for fresh installs and explicit reactivations.
 */
register_activation_hook(
	FRAK_PLUGIN_FILE,
	static function () {
		Frak_Settings::migrate();
		flush_rewrite_rules();
	}
);

/**
 * Run the settings migration after the plugin is updated via the WordPress
 * updater — `register_activation_hook` does not fire on in-place upgrades,
 * so this covers the "bump CURRENT_VERSION, ship a new migration step" case.
 *
 * @param WP_Upgrader $upgrader Unused (required by signature).
 * @param array       $options  Hook payload describing the upgrade batch.
 */
add_action(
	'upgrader_process_complete',
	static function ( $upgrader, $options ) {
		unset( $upgrader );
		if ( ! isset( $options['action'], $options['type'], $options['plugins'] ) ) {
			return;
		}
		if ( 'update' !== $options['action'] || 'plugin' !== $options['type'] ) {
			return;
		}
		if ( ! is_array( $options['plugins'] ) ) {
			return;
		}
		if ( ! in_array( plugin_basename( FRAK_PLUGIN_FILE ), $options['plugins'], true ) ) {
			return;
		}
		Frak_Settings::migrate();
	},
	10,
	2
);

/**
 * Declare compatibility with WooCommerce High-Performance Order Storage (HPOS / custom order tables).
 */
add_action(
	'before_woocommerce_init',
	static function () {
		if ( class_exists( \Automattic\WooCommerce\Utilities\FeaturesUtil::class ) ) {
			\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility( 'custom_order_tables', FRAK_PLUGIN_FILE, true );
		}
	}
);
