package id.frak.sdk.identity

import id.frak.sdk.fixtures.GoldenFixtures
import id.frak.sdk.identity.TestKeys.hexToBytes
import id.frak.sdk.identity.TestKeys.toHex
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertThrows
import org.junit.Test
import java.security.MessageDigest
import java.security.Signature

/**
 * The identity wire format against the shared corpus.
 *
 * These are the vectors the TypeScript signer and the backend verifier are also
 * asserted against, so a divergence here is a divergence from the contract, not
 * a disagreement between two Kotlin opinions.
 *
 * The fixture signatures are **not** compared byte-for-byte against a signature
 * produced here: the corpus is generated by a deterministic (RFC 6979) signer
 * and JCA's is randomised, so equal signatures would only ever mean equal
 * nonces. They are verified instead — which is what a backend does anyway, and
 * which additionally exercises the raw↔DER conversion in both directions.
 */
class ProofCodecTest {
    private val corpus = GoldenFixtures.load(GoldenFixtures.IDENTITY_PROOFS)

    @Test
    fun `derives every fixture's client id from its public key`() {
        for (fixture in corpus.entries) {
            val publicKey = hexToBytes(fixture.getString("pubkeyUncompressedHex"))
            val hash = MessageDigest.getInstance("SHA-256").digest(publicKey)
            assertEquals(
                fixture.getString("description"),
                fixture.getString("derivedClientId"),
                ProofCodec.deriveClientIdFromHash(hash),
            )
        }
    }

    @Test
    fun `builds every fixture's canonical message byte-for-byte`() {
        val covered = mutableSetOf<ProofOp>()
        for (fixture in corpus.entries) {
            val op = opOf(fixture.getString("op")) ?: continue
            covered += op
            val message =
                ProofCodec.buildMessage(
                    op = op,
                    merchantId = fixture.getString("merchantId"),
                    anonymousId = fixture.getString("anonymousId"),
                    binding = hexToBytes(fixture.getString("bindingHex")),
                    ts = fixture.getLong("ts"),
                )
            assertEquals(
                fixture.getString("description"),
                fixture.getString("canonicalMsgHex"),
                message.toHex(),
            )
        }
        assertEquals("every op this SDK can mint must have a fixture", ProofOp.entries.toSet(), covered)
    }

    @Test
    fun `encodes every fixture's proof envelope`() {
        for (fixture in corpus.entries) {
            val proof =
                ProofCodec.encodeProof(
                    publicKey = hexToBytes(fixture.getString("pubkeyUncompressedHex")),
                    ts = fixture.getLong("ts"),
                    signature = hexToBytes(fixture.getString("sigHex")),
                )
            assertEquals(fixture.getString("description"), fixture.getString("proof"), proof)
        }
    }

    /**
     * Round-trips each fixture signature through DER and back, then checks it
     * verifies against the canonical message. Covers the conversion JCA forces
     * on us in both directions, on real coordinates including the short and
     * high-bit-set cases the corpus happens to contain.
     */
    @Test
    fun `fixture signatures verify against their canonical message`() {
        for (fixture in corpus.entries) {
            val raw = hexToBytes(fixture.getString("sigHex"))
            assertArrayEquals(
                "raw -> DER -> raw is not lossless: ${fixture.getString("description")}",
                raw,
                JcaDeviceKey.derToRawSignature(TestKeys.rawToDerSignature(raw)),
            )

            val verifier = Signature.getInstance(JcaDeviceKey.SIGNATURE_ALGORITHM)
            val publicKey = TestKeys.publicKeyFromUncompressed(hexToBytes(fixture.getString("pubkeyUncompressedHex")))
            verifier.initVerify(publicKey)
            verifier.update(hexToBytes(fixture.getString("canonicalMsgHex")))
            assert(verifier.verify(TestKeys.rawToDerSignature(raw))) {
                "signature does not verify: ${fixture.getString("description")}"
            }
        }
    }

    @Test
    fun `signs and verifies with a freshly generated key`() {
        val key = TestKeys.generate()
        val message = ProofCodec.buildMessage(ProofOp.Ensure, MERCHANT_ID, ANONYMOUS_ID, ByteArray(0), 1_700_000_000)

        val signature = key.sign(message)
        assertEquals(ProofCodec.SIG_BYTES, signature.size)

        val verifier = Signature.getInstance(JcaDeviceKey.SIGNATURE_ALGORITHM)
        verifier.initVerify(TestKeys.publicKeyFromUncompressed(key.publicKeyUncompressed))
        verifier.update(message)
        assert(verifier.verify(TestKeys.rawToDerSignature(signature)))
    }

    @Test
    fun `derives the same id for the same key regardless of uuid case`() {
        val upper = ProofCodec.buildMessage(ProofOp.Ensure, MERCHANT_ID.uppercase(), ANONYMOUS_ID, ByteArray(0), 1)
        val lower = ProofCodec.buildMessage(ProofOp.Ensure, MERCHANT_ID, ANONYMOUS_ID, ByteArray(0), 1)
        assertArrayEquals(lower, upper)
    }

    @Test
    fun `rejects a binding that is neither empty nor 32 bytes`() {
        assertThrows(IllegalArgumentException::class.java) {
            ProofCodec.buildMessage(ProofOp.Merge, MERCHANT_ID, ANONYMOUS_ID, ByteArray(31), 1)
        }
    }

    @Test
    fun `rejects a malformed uuid`() {
        assertThrows(IllegalArgumentException::class.java) {
            ProofCodec.buildMessage(ProofOp.Ensure, "not-a-uuid", ANONYMOUS_ID, ByteArray(0), 1)
        }
    }

    @Test
    fun `rejects a public key or signature of the wrong width`() {
        assertThrows(IllegalArgumentException::class.java) {
            ProofCodec.encodeProof(ByteArray(64), 1, ByteArray(ProofCodec.SIG_BYTES))
        }
        assertThrows(IllegalArgumentException::class.java) {
            ProofCodec.encodeProof(ByteArray(ProofCodec.PUBKEY_BYTES), 1, ByteArray(63))
        }
    }

    @Test
    fun `rejects a der signature that is not one of ours`() {
        assertThrows(IllegalArgumentException::class.java) {
            JcaDeviceKey.derToRawSignature(ByteArray(8))
        }
        // Long-form SEQUENCE length: valid DER, but never a P-256 signature.
        assertNull(
            runCatching {
                JcaDeviceKey.derToRawSignature(
                    byteArrayOf(0x30, 0x81.toByte(), 0x46, 0x02, 0x01, 0x01, 0x02, 0x01, 0x01),
                )
            }.getOrNull(),
        )
    }

    /**
     * Null for an op this SDK cannot mint. The corpus is shared with the web
     * SDK, which also covers `frak-sso-v1`; native has no SSO surface, so
     * declaring an arm for it would be an unused public-ish symbol rather than
     * extra coverage. `covered` above is what stops that becoming a silent hole.
     */
    private fun opOf(wireValue: String): ProofOp? = ProofOp.entries.firstOrNull { it.wireValue == wireValue }

    private companion object {
        const val MERCHANT_ID = "9c8b3e2a-1d4f-4a6b-8e2d-7f3a1b5c9d0e"
        const val ANONYMOUS_ID = "256b1be3-2745-41d1-89d4-9121cc87bc45"
    }
}
