import { PgDialect } from "drizzle-orm/pg-core";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { PurchaseRepository } from "./PurchaseRepository";

// Mock the DB layer the same way ReferralLinkRepository.test.ts does: no
// live DB, just chainable vi.fn() stand-ins for the Drizzle query builder.
// upsertWithItems runs inside db.transaction((trx) => ...), so the trx
// handle needs the same chainable shape as `db` itself. We distinguish the
// purchases-insert chain from the items-insert chain by call order (first
// trx.insert() call is always the purchase, the second is always the
// items) rather than table identity, since vi.mock factories are hoisted
// above the schema import and can't reference it directly.
//
// The purchases chain also captures the `set` block passed to
// `.onConflictDoUpdate(...)` so tests can assert on the exact upsert
// semantics generated by `upsertWithItems` (e.g. rendering the raw SQL for
// the identityGroupId COALESCE guard).
const {
    mockPurchaseValues,
    mockPurchaseReturning,
    mockItemsValues,
    mockItemsOnConflictDoNothing,
    mockSelectWhere,
    capturedSetRef,
} = vi.hoisted(() => ({
    mockPurchaseValues: vi.fn(),
    mockPurchaseReturning: vi.fn(),
    mockItemsValues: vi.fn(),
    mockItemsOnConflictDoNothing: vi.fn(),
    mockSelectWhere: vi.fn(),
    capturedSetRef: { current: null as any },
}));

vi.mock("@backend-infrastructure", () => ({
    log: { debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() },
    db: {
        select: vi.fn().mockReturnThis(),
        from: vi.fn().mockReturnThis(),
        where: mockSelectWhere,
        transaction: vi.fn(async (cb: (trx: unknown) => unknown) => {
            let insertCallCount = 0;
            const trx = {
                insert: vi.fn(() => {
                    insertCallCount++;
                    if (insertCallCount === 1) {
                        // purchasesTable: .values().onConflictDoUpdate().returning()
                        const purchaseChain = {
                            values: mockPurchaseValues.mockImplementation(
                                () => purchaseChain
                            ),
                            onConflictDoUpdate: vi.fn((args: any) => {
                                capturedSetRef.current = args.set;
                                return purchaseChain;
                            }),
                            returning: mockPurchaseReturning,
                        };
                        return purchaseChain;
                    }
                    // purchaseItemsTable: .values().onConflictDoNothing()
                    const itemsChain = {
                        values: mockItemsValues.mockImplementation(
                            () => itemsChain
                        ),
                        onConflictDoNothing: mockItemsOnConflictDoNothing,
                    };
                    return itemsChain;
                }),
            };
            return cb(trx);
        }),
    },
}));

const pgDialect = new PgDialect();

const basePurchase = {
    externalId: "order-1",
    webhookId: 1,
    externalCustomerId: "cust-1",
    totalPrice: "42.00",
    currencyCode: "USD",
    status: "paid" as const,
};

describe("PurchaseRepository", () => {
    beforeEach(() => {
        mockPurchaseValues.mockReset();
        mockPurchaseReturning.mockReset();
        mockPurchaseReturning.mockResolvedValue([{ purchaseId: "purchase-1" }]);
        mockItemsValues.mockReset();
        mockItemsOnConflictDoNothing.mockReset();
        mockItemsOnConflictDoNothing.mockResolvedValue(undefined);
        mockSelectWhere.mockReset();
        mockSelectWhere.mockResolvedValue([]);
        capturedSetRef.current = null;
    });

    describe("upsertWithItems — identityGroupId attribution", () => {
        it("fills identityGroupId via SQL COALESCE when the caller supplies one (first-writer-wins, not a JS check)", async () => {
            const repo = new PurchaseRepository();
            const newGroupId = "22222222-2222-2222-2222-222222222222";

            await repo.upsertWithItems({
                purchase: basePurchase,
                items: [],
                identityGroupId: newGroupId,
            });

            const set = capturedSetRef.current;
            expect(set.identityGroupId).toBeDefined();

            // Render the actual SQL: proves (a) COALESCE is used, (b) the bare
            // column reference resolves to the EXISTING row ("purchases" table,
            // not "excluded"), and (c) the supplied value is only the fallback —
            // exactly the semantics that make a redelivery unable to clobber an
            // already-set attribution.
            const rendered = pgDialect.sqlToQuery(set.identityGroupId);
            expect(rendered.sql).toBe(
                'coalesce("purchases"."identity_group_id", $1)'
            );
            expect(rendered.params).toEqual([newGroupId]);
        });

        it("never nulls out an existing group when the delivery supplies none", async () => {
            const repo = new PurchaseRepository();

            await repo.upsertWithItems({
                purchase: basePurchase,
                items: [],
            });

            const set = capturedSetRef.current;
            // Key must be absent entirely, not set to undefined/null — an absent
            // key leaves the column untouched in the SET clause.
            expect("identityGroupId" in set).toBe(false);
        });

        it("still updates status, totalPrice, currencyCode, updatedAt and purchaseToken (guard does not freeze the rest of the row)", async () => {
            const repo = new PurchaseRepository();

            await repo.upsertWithItems({
                purchase: {
                    ...basePurchase,
                    status: "refunded" as const,
                    totalPrice: "50.00",
                    currencyCode: "EUR",
                    purchaseToken: "tok-123",
                },
                items: [],
                identityGroupId: "33333333-3333-3333-3333-333333333333",
            });

            const set = capturedSetRef.current;
            expect(set.status).toBe("refunded");
            expect(set.totalPrice).toBe("50.00");
            expect(set.currencyCode).toBe("EUR");
            expect(set.purchaseToken).toBe("tok-123");
            expect(set.updatedAt).toBeInstanceOf(Date);
        });
    });

    describe("upsertWithItems — items", () => {
        it("passes sku through into the inserted item values", async () => {
            const repository = new PurchaseRepository();

            await repository.upsertWithItems({
                purchase: {
                    externalId: "order-1",
                    webhookId: 1,
                    status: "paid",
                    totalPrice: "10.00",
                    currencyCode: "usd",
                } as never,
                items: [
                    {
                        externalId: "item-1",
                        price: "10.00",
                        name: "Widget",
                        title: "Widget",
                        quantity: 1,
                        sku: "SKU-123",
                    } as never,
                ],
            });

            expect(mockItemsValues).toHaveBeenCalledWith([
                expect.objectContaining({
                    sku: "SKU-123",
                    purchaseId: "purchase-1",
                }),
            ]);
        });

        it("does not insert items when the list is empty", async () => {
            const repository = new PurchaseRepository();

            await repository.upsertWithItems({
                purchase: {
                    externalId: "order-1",
                    webhookId: 1,
                    status: "paid",
                    totalPrice: "10.00",
                    currencyCode: "usd",
                } as never,
                items: [],
            });

            expect(mockItemsValues).not.toHaveBeenCalled();
        });
    });

    describe("findItemsByPurchaseId", () => {
        it("projects every column via a bare select (sku not stripped)", async () => {
            mockSelectWhere.mockResolvedValue([
                {
                    id: "item-1",
                    purchaseId: "purchase-1",
                    externalId: "ext-1",
                    price: "10.00",
                    name: "Widget",
                    title: "Widget",
                    imageUrl: null,
                    quantity: 1,
                    sku: "SKU-123",
                    createdAt: new Date(),
                },
            ]);

            const repository = new PurchaseRepository();
            const items = await repository.findItemsByPurchaseId("purchase-1");

            expect(items).toHaveLength(1);
            expect(items[0]?.sku).toBe("SKU-123");
        });
    });
});
