# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "49291fc2a1e5a5c9fb9d94a4b53994a6"
application_url = "https://example.com/"
embedded = true
name = "frak-shop-app"
handle = "frak-shop-app"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
