/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as RestrictedRouteImport } from './routes/_restricted'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbeddedAuthRouteImport } from './routes/embedded/auth'
import { Route as EmbeddedLayoutRouteImport } from './routes/embedded/_layout'
import { Route as RestrictedSettingsRouteImport } from './routes/_restricted/settings'
import { Route as RestrictedMembersRouteImport } from './routes/_restricted/members'
import { Route as RestrictedDashboardRouteImport } from './routes/_restricted/dashboard'
import { Route as EmbeddedLayoutMintRouteImport } from './routes/embedded/_layout/mint'
import { Route as RestrictedPushCreateRouteImport } from './routes/_restricted/push/create'
import { Route as RestrictedPushConfirmRouteImport } from './routes/_restricted/push/confirm'
import { Route as RestrictedMMerchantIdRouteImport } from './routes/_restricted/m/$merchantId'
import { Route as RestrictedCampaignsOverviewRouteImport } from './routes/_restricted/campaigns/overview'
import { Route as RestrictedCampaignsListRouteImport } from './routes/_restricted/campaigns/list'
import { Route as RestrictedCampaignsCampaignIdRouteImport } from './routes/_restricted/campaigns/$campaignId'
import { Route as RestrictedMerchantIdIndexRouteImport } from './routes/_restricted/merchant/$id/index'
import { Route as RestrictedMerchantIdTeamRouteImport } from './routes/_restricted/merchant/$id/team'
import { Route as RestrictedMerchantIdSetupStatusRouteImport } from './routes/_restricted/merchant/$id/setup-status'
import { Route as RestrictedMerchantIdFundingRouteImport } from './routes/_restricted/merchant/$id/funding'
import { Route as RestrictedMerchantIdCustomizeRouteImport } from './routes/_restricted/merchant/$id/customize'
import { Route as RestrictedMMerchantIdMembersRouteImport } from './routes/_restricted/m/$merchantId/members'
import { Route as RestrictedMMerchantIdDashboardRouteImport } from './routes/_restricted/m/$merchantId/dashboard'
import { Route as RestrictedCampaignsEditCampaignIdRouteImport } from './routes/_restricted/campaigns/edit/$campaignId'
import { Route as RestrictedCampaignsDraftNewRouteImport } from './routes/_restricted/campaigns/draft/new'
import { Route as RestrictedMMerchantIdMerchantIndexRouteImport } from './routes/_restricted/m/$merchantId/merchant/index'
import { Route as RestrictedCampaignsDraftCampaignIdIndexRouteImport } from './routes/_restricted/campaigns/draft/$campaignId/index'
import { Route as RestrictedMMerchantIdPushCreateRouteImport } from './routes/_restricted/m/$merchantId/push/create'
import { Route as RestrictedMMerchantIdPushConfirmRouteImport } from './routes/_restricted/m/$merchantId/push/confirm'
import { Route as RestrictedMMerchantIdMerchantTeamRouteImport } from './routes/_restricted/m/$merchantId/merchant/team'
import { Route as RestrictedMMerchantIdMerchantSetupStatusRouteImport } from './routes/_restricted/m/$merchantId/merchant/setup-status'
import { Route as RestrictedMMerchantIdMerchantFundingRouteImport } from './routes/_restricted/m/$merchantId/merchant/funding'
import { Route as RestrictedMMerchantIdMerchantCustomizeRouteImport } from './routes/_restricted/m/$merchantId/merchant/customize'
import { Route as RestrictedMMerchantIdCampaignsOverviewRouteImport } from './routes/_restricted/m/$merchantId/campaigns/overview'
import { Route as RestrictedMMerchantIdCampaignsListRouteImport } from './routes/_restricted/m/$merchantId/campaigns/list'
import { Route as RestrictedMMerchantIdCampaignsCampaignIdRouteImport } from './routes/_restricted/m/$merchantId/campaigns/$campaignId'
import { Route as RestrictedCampaignsDraftCampaignIdValidationRouteImport } from './routes/_restricted/campaigns/draft/$campaignId/validation'
import { Route as RestrictedCampaignsDraftCampaignIdMetricsRouteImport } from './routes/_restricted/campaigns/draft/$campaignId/metrics'
import { Route as RestrictedMMerchantIdCampaignsEditCampaignIdRouteImport } from './routes/_restricted/m/$merchantId/campaigns/edit/$campaignId'
import { Route as RestrictedMMerchantIdCampaignsDraftNewRouteImport } from './routes/_restricted/m/$merchantId/campaigns/draft/new'
import { Route as RestrictedMMerchantIdCampaignsDraftCampaignIdIndexRouteImport } from './routes/_restricted/m/$merchantId/campaigns/draft/$campaignId/index'
import { Route as RestrictedMMerchantIdCampaignsDraftCampaignIdValidationRouteImport } from './routes/_restricted/m/$merchantId/campaigns/draft/$campaignId/validation'
import { Route as RestrictedMMerchantIdCampaignsDraftCampaignIdMetricsRouteImport } from './routes/_restricted/m/$merchantId/campaigns/draft/$campaignId/metrics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const RestrictedRoute = RestrictedRouteImport.update({
  id: '/_restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddedAuthRoute = EmbeddedAuthRouteImport.update({
  id: '/embedded/auth',
  path: '/embedded/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddedLayoutRoute = EmbeddedLayoutRouteImport.update({
  id: '/embedded/_layout',
  path: '/embedded',
  getParentRoute: () => rootRouteImport,
} as any)
const RestrictedSettingsRoute = RestrictedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedMembersRoute = RestrictedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedDashboardRoute = RestrictedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RestrictedRoute,
} as any)
const EmbeddedLayoutMintRoute = EmbeddedLayoutMintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => EmbeddedLayoutRoute,
} as any)
const RestrictedPushCreateRoute = RestrictedPushCreateRouteImport.update({
  id: '/push/create',
  path: '/push/create',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedPushConfirmRoute = RestrictedPushConfirmRouteImport.update({
  id: '/push/confirm',
  path: '/push/confirm',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedMMerchantIdRoute = RestrictedMMerchantIdRouteImport.update({
  id: '/m/$merchantId',
  path: '/m/$merchantId',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedCampaignsOverviewRoute =
  RestrictedCampaignsOverviewRouteImport.update({
    id: '/campaigns/overview',
    path: '/campaigns/overview',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsListRoute = RestrictedCampaignsListRouteImport.update({
  id: '/campaigns/list',
  path: '/campaigns/list',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedCampaignsCampaignIdRoute =
  RestrictedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMerchantIdIndexRoute =
  RestrictedMerchantIdIndexRouteImport.update({
    id: '/merchant/$id/',
    path: '/merchant/$id/',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMerchantIdTeamRoute =
  RestrictedMerchantIdTeamRouteImport.update({
    id: '/merchant/$id/team',
    path: '/merchant/$id/team',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMerchantIdSetupStatusRoute =
  RestrictedMerchantIdSetupStatusRouteImport.update({
    id: '/merchant/$id/setup-status',
    path: '/merchant/$id/setup-status',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMerchantIdFundingRoute =
  RestrictedMerchantIdFundingRouteImport.update({
    id: '/merchant/$id/funding',
    path: '/merchant/$id/funding',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMerchantIdCustomizeRoute =
  RestrictedMerchantIdCustomizeRouteImport.update({
    id: '/merchant/$id/customize',
    path: '/merchant/$id/customize',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMMerchantIdMembersRoute =
  RestrictedMMerchantIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdDashboardRoute =
  RestrictedMMerchantIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedCampaignsEditCampaignIdRoute =
  RestrictedCampaignsEditCampaignIdRouteImport.update({
    id: '/campaigns/edit/$campaignId',
    path: '/campaigns/edit/$campaignId',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsDraftNewRoute =
  RestrictedCampaignsDraftNewRouteImport.update({
    id: '/campaigns/draft/new',
    path: '/campaigns/draft/new',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMMerchantIdMerchantIndexRoute =
  RestrictedMMerchantIdMerchantIndexRouteImport.update({
    id: '/merchant/',
    path: '/merchant/',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedCampaignsDraftCampaignIdIndexRoute =
  RestrictedCampaignsDraftCampaignIdIndexRouteImport.update({
    id: '/campaigns/draft/$campaignId/',
    path: '/campaigns/draft/$campaignId/',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMMerchantIdPushCreateRoute =
  RestrictedMMerchantIdPushCreateRouteImport.update({
    id: '/push/create',
    path: '/push/create',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdPushConfirmRoute =
  RestrictedMMerchantIdPushConfirmRouteImport.update({
    id: '/push/confirm',
    path: '/push/confirm',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdMerchantTeamRoute =
  RestrictedMMerchantIdMerchantTeamRouteImport.update({
    id: '/merchant/team',
    path: '/merchant/team',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdMerchantSetupStatusRoute =
  RestrictedMMerchantIdMerchantSetupStatusRouteImport.update({
    id: '/merchant/setup-status',
    path: '/merchant/setup-status',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdMerchantFundingRoute =
  RestrictedMMerchantIdMerchantFundingRouteImport.update({
    id: '/merchant/funding',
    path: '/merchant/funding',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdMerchantCustomizeRoute =
  RestrictedMMerchantIdMerchantCustomizeRouteImport.update({
    id: '/merchant/customize',
    path: '/merchant/customize',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdCampaignsOverviewRoute =
  RestrictedMMerchantIdCampaignsOverviewRouteImport.update({
    id: '/campaigns/overview',
    path: '/campaigns/overview',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdCampaignsListRoute =
  RestrictedMMerchantIdCampaignsListRouteImport.update({
    id: '/campaigns/list',
    path: '/campaigns/list',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdCampaignsCampaignIdRoute =
  RestrictedMMerchantIdCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedCampaignsDraftCampaignIdValidationRoute =
  RestrictedCampaignsDraftCampaignIdValidationRouteImport.update({
    id: '/campaigns/draft/$campaignId/validation',
    path: '/campaigns/draft/$campaignId/validation',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsDraftCampaignIdMetricsRoute =
  RestrictedCampaignsDraftCampaignIdMetricsRouteImport.update({
    id: '/campaigns/draft/$campaignId/metrics',
    path: '/campaigns/draft/$campaignId/metrics',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMMerchantIdCampaignsEditCampaignIdRoute =
  RestrictedMMerchantIdCampaignsEditCampaignIdRouteImport.update({
    id: '/campaigns/edit/$campaignId',
    path: '/campaigns/edit/$campaignId',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdCampaignsDraftNewRoute =
  RestrictedMMerchantIdCampaignsDraftNewRouteImport.update({
    id: '/campaigns/draft/new',
    path: '/campaigns/draft/new',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdCampaignsDraftCampaignIdIndexRoute =
  RestrictedMMerchantIdCampaignsDraftCampaignIdIndexRouteImport.update({
    id: '/campaigns/draft/$campaignId/',
    path: '/campaigns/draft/$campaignId/',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdCampaignsDraftCampaignIdValidationRoute =
  RestrictedMMerchantIdCampaignsDraftCampaignIdValidationRouteImport.update({
    id: '/campaigns/draft/$campaignId/validation',
    path: '/campaigns/draft/$campaignId/validation',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)
const RestrictedMMerchantIdCampaignsDraftCampaignIdMetricsRoute =
  RestrictedMMerchantIdCampaignsDraftCampaignIdMetricsRouteImport.update({
    id: '/campaigns/draft/$campaignId/metrics',
    path: '/campaigns/draft/$campaignId/metrics',
    getParentRoute: () => RestrictedMMerchantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof RestrictedDashboardRoute
  '/members': typeof RestrictedMembersRoute
  '/settings': typeof RestrictedSettingsRoute
  '/embedded': typeof EmbeddedLayoutRouteWithChildren
  '/embedded/auth': typeof EmbeddedAuthRoute
  '/campaigns/$campaignId': typeof RestrictedCampaignsCampaignIdRoute
  '/campaigns/list': typeof RestrictedCampaignsListRoute
  '/campaigns/overview': typeof RestrictedCampaignsOverviewRoute
  '/m/$merchantId': typeof RestrictedMMerchantIdRouteWithChildren
  '/push/confirm': typeof RestrictedPushConfirmRoute
  '/push/create': typeof RestrictedPushCreateRoute
  '/embedded/mint': typeof EmbeddedLayoutMintRoute
  '/campaigns/draft/new': typeof RestrictedCampaignsDraftNewRoute
  '/campaigns/edit/$campaignId': typeof RestrictedCampaignsEditCampaignIdRoute
  '/m/$merchantId/dashboard': typeof RestrictedMMerchantIdDashboardRoute
  '/m/$merchantId/members': typeof RestrictedMMerchantIdMembersRoute
  '/merchant/$id/customize': typeof RestrictedMerchantIdCustomizeRoute
  '/merchant/$id/funding': typeof RestrictedMerchantIdFundingRoute
  '/merchant/$id/setup-status': typeof RestrictedMerchantIdSetupStatusRoute
  '/merchant/$id/team': typeof RestrictedMerchantIdTeamRoute
  '/merchant/$id/': typeof RestrictedMerchantIdIndexRoute
  '/campaigns/draft/$campaignId/metrics': typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  '/campaigns/draft/$campaignId/validation': typeof RestrictedCampaignsDraftCampaignIdValidationRoute
  '/m/$merchantId/campaigns/$campaignId': typeof RestrictedMMerchantIdCampaignsCampaignIdRoute
  '/m/$merchantId/campaigns/list': typeof RestrictedMMerchantIdCampaignsListRoute
  '/m/$merchantId/campaigns/overview': typeof RestrictedMMerchantIdCampaignsOverviewRoute
  '/m/$merchantId/merchant/customize': typeof RestrictedMMerchantIdMerchantCustomizeRoute
  '/m/$merchantId/merchant/funding': typeof RestrictedMMerchantIdMerchantFundingRoute
  '/m/$merchantId/merchant/setup-status': typeof RestrictedMMerchantIdMerchantSetupStatusRoute
  '/m/$merchantId/merchant/team': typeof RestrictedMMerchantIdMerchantTeamRoute
  '/m/$merchantId/push/confirm': typeof RestrictedMMerchantIdPushConfirmRoute
  '/m/$merchantId/push/create': typeof RestrictedMMerchantIdPushCreateRoute
  '/campaigns/draft/$campaignId/': typeof RestrictedCampaignsDraftCampaignIdIndexRoute
  '/m/$merchantId/merchant/': typeof RestrictedMMerchantIdMerchantIndexRoute
  '/m/$merchantId/campaigns/draft/new': typeof RestrictedMMerchantIdCampaignsDraftNewRoute
  '/m/$merchantId/campaigns/edit/$campaignId': typeof RestrictedMMerchantIdCampaignsEditCampaignIdRoute
  '/m/$merchantId/campaigns/draft/$campaignId/metrics': typeof RestrictedMMerchantIdCampaignsDraftCampaignIdMetricsRoute
  '/m/$merchantId/campaigns/draft/$campaignId/validation': typeof RestrictedMMerchantIdCampaignsDraftCampaignIdValidationRoute
  '/m/$merchantId/campaigns/draft/$campaignId/': typeof RestrictedMMerchantIdCampaignsDraftCampaignIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof RestrictedDashboardRoute
  '/members': typeof RestrictedMembersRoute
  '/settings': typeof RestrictedSettingsRoute
  '/embedded': typeof EmbeddedLayoutRouteWithChildren
  '/embedded/auth': typeof EmbeddedAuthRoute
  '/campaigns/$campaignId': typeof RestrictedCampaignsCampaignIdRoute
  '/campaigns/list': typeof RestrictedCampaignsListRoute
  '/campaigns/overview': typeof RestrictedCampaignsOverviewRoute
  '/m/$merchantId': typeof RestrictedMMerchantIdRouteWithChildren
  '/push/confirm': typeof RestrictedPushConfirmRoute
  '/push/create': typeof RestrictedPushCreateRoute
  '/embedded/mint': typeof EmbeddedLayoutMintRoute
  '/campaigns/draft/new': typeof RestrictedCampaignsDraftNewRoute
  '/campaigns/edit/$campaignId': typeof RestrictedCampaignsEditCampaignIdRoute
  '/m/$merchantId/dashboard': typeof RestrictedMMerchantIdDashboardRoute
  '/m/$merchantId/members': typeof RestrictedMMerchantIdMembersRoute
  '/merchant/$id/customize': typeof RestrictedMerchantIdCustomizeRoute
  '/merchant/$id/funding': typeof RestrictedMerchantIdFundingRoute
  '/merchant/$id/setup-status': typeof RestrictedMerchantIdSetupStatusRoute
  '/merchant/$id/team': typeof RestrictedMerchantIdTeamRoute
  '/merchant/$id': typeof RestrictedMerchantIdIndexRoute
  '/campaigns/draft/$campaignId/metrics': typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  '/campaigns/draft/$campaignId/validation': typeof RestrictedCampaignsDraftCampaignIdValidationRoute
  '/m/$merchantId/campaigns/$campaignId': typeof RestrictedMMerchantIdCampaignsCampaignIdRoute
  '/m/$merchantId/campaigns/list': typeof RestrictedMMerchantIdCampaignsListRoute
  '/m/$merchantId/campaigns/overview': typeof RestrictedMMerchantIdCampaignsOverviewRoute
  '/m/$merchantId/merchant/customize': typeof RestrictedMMerchantIdMerchantCustomizeRoute
  '/m/$merchantId/merchant/funding': typeof RestrictedMMerchantIdMerchantFundingRoute
  '/m/$merchantId/merchant/setup-status': typeof RestrictedMMerchantIdMerchantSetupStatusRoute
  '/m/$merchantId/merchant/team': typeof RestrictedMMerchantIdMerchantTeamRoute
  '/m/$merchantId/push/confirm': typeof RestrictedMMerchantIdPushConfirmRoute
  '/m/$merchantId/push/create': typeof RestrictedMMerchantIdPushCreateRoute
  '/campaigns/draft/$campaignId': typeof RestrictedCampaignsDraftCampaignIdIndexRoute
  '/m/$merchantId/merchant': typeof RestrictedMMerchantIdMerchantIndexRoute
  '/m/$merchantId/campaigns/draft/new': typeof RestrictedMMerchantIdCampaignsDraftNewRoute
  '/m/$merchantId/campaigns/edit/$campaignId': typeof RestrictedMMerchantIdCampaignsEditCampaignIdRoute
  '/m/$merchantId/campaigns/draft/$campaignId/metrics': typeof RestrictedMMerchantIdCampaignsDraftCampaignIdMetricsRoute
  '/m/$merchantId/campaigns/draft/$campaignId/validation': typeof RestrictedMMerchantIdCampaignsDraftCampaignIdValidationRoute
  '/m/$merchantId/campaigns/draft/$campaignId': typeof RestrictedMMerchantIdCampaignsDraftCampaignIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_restricted': typeof RestrictedRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/_restricted/dashboard': typeof RestrictedDashboardRoute
  '/_restricted/members': typeof RestrictedMembersRoute
  '/_restricted/settings': typeof RestrictedSettingsRoute
  '/embedded/_layout': typeof EmbeddedLayoutRouteWithChildren
  '/embedded/auth': typeof EmbeddedAuthRoute
  '/_restricted/campaigns/$campaignId': typeof RestrictedCampaignsCampaignIdRoute
  '/_restricted/campaigns/list': typeof RestrictedCampaignsListRoute
  '/_restricted/campaigns/overview': typeof RestrictedCampaignsOverviewRoute
  '/_restricted/m/$merchantId': typeof RestrictedMMerchantIdRouteWithChildren
  '/_restricted/push/confirm': typeof RestrictedPushConfirmRoute
  '/_restricted/push/create': typeof RestrictedPushCreateRoute
  '/embedded/_layout/mint': typeof EmbeddedLayoutMintRoute
  '/_restricted/campaigns/draft/new': typeof RestrictedCampaignsDraftNewRoute
  '/_restricted/campaigns/edit/$campaignId': typeof RestrictedCampaignsEditCampaignIdRoute
  '/_restricted/m/$merchantId/dashboard': typeof RestrictedMMerchantIdDashboardRoute
  '/_restricted/m/$merchantId/members': typeof RestrictedMMerchantIdMembersRoute
  '/_restricted/merchant/$id/customize': typeof RestrictedMerchantIdCustomizeRoute
  '/_restricted/merchant/$id/funding': typeof RestrictedMerchantIdFundingRoute
  '/_restricted/merchant/$id/setup-status': typeof RestrictedMerchantIdSetupStatusRoute
  '/_restricted/merchant/$id/team': typeof RestrictedMerchantIdTeamRoute
  '/_restricted/merchant/$id/': typeof RestrictedMerchantIdIndexRoute
  '/_restricted/campaigns/draft/$campaignId/metrics': typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  '/_restricted/campaigns/draft/$campaignId/validation': typeof RestrictedCampaignsDraftCampaignIdValidationRoute
  '/_restricted/m/$merchantId/campaigns/$campaignId': typeof RestrictedMMerchantIdCampaignsCampaignIdRoute
  '/_restricted/m/$merchantId/campaigns/list': typeof RestrictedMMerchantIdCampaignsListRoute
  '/_restricted/m/$merchantId/campaigns/overview': typeof RestrictedMMerchantIdCampaignsOverviewRoute
  '/_restricted/m/$merchantId/merchant/customize': typeof RestrictedMMerchantIdMerchantCustomizeRoute
  '/_restricted/m/$merchantId/merchant/funding': typeof RestrictedMMerchantIdMerchantFundingRoute
  '/_restricted/m/$merchantId/merchant/setup-status': typeof RestrictedMMerchantIdMerchantSetupStatusRoute
  '/_restricted/m/$merchantId/merchant/team': typeof RestrictedMMerchantIdMerchantTeamRoute
  '/_restricted/m/$merchantId/push/confirm': typeof RestrictedMMerchantIdPushConfirmRoute
  '/_restricted/m/$merchantId/push/create': typeof RestrictedMMerchantIdPushCreateRoute
  '/_restricted/campaigns/draft/$campaignId/': typeof RestrictedCampaignsDraftCampaignIdIndexRoute
  '/_restricted/m/$merchantId/merchant/': typeof RestrictedMMerchantIdMerchantIndexRoute
  '/_restricted/m/$merchantId/campaigns/draft/new': typeof RestrictedMMerchantIdCampaignsDraftNewRoute
  '/_restricted/m/$merchantId/campaigns/edit/$campaignId': typeof RestrictedMMerchantIdCampaignsEditCampaignIdRoute
  '/_restricted/m/$merchantId/campaigns/draft/$campaignId/metrics': typeof RestrictedMMerchantIdCampaignsDraftCampaignIdMetricsRoute
  '/_restricted/m/$merchantId/campaigns/draft/$campaignId/validation': typeof RestrictedMMerchantIdCampaignsDraftCampaignIdValidationRoute
  '/_restricted/m/$merchantId/campaigns/draft/$campaignId/': typeof RestrictedMMerchantIdCampaignsDraftCampaignIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/dashboard'
    | '/members'
    | '/settings'
    | '/embedded'
    | '/embedded/auth'
    | '/campaigns/$campaignId'
    | '/campaigns/list'
    | '/campaigns/overview'
    | '/m/$merchantId'
    | '/push/confirm'
    | '/push/create'
    | '/embedded/mint'
    | '/campaigns/draft/new'
    | '/campaigns/edit/$campaignId'
    | '/m/$merchantId/dashboard'
    | '/m/$merchantId/members'
    | '/merchant/$id/customize'
    | '/merchant/$id/funding'
    | '/merchant/$id/setup-status'
    | '/merchant/$id/team'
    | '/merchant/$id/'
    | '/campaigns/draft/$campaignId/metrics'
    | '/campaigns/draft/$campaignId/validation'
    | '/m/$merchantId/campaigns/$campaignId'
    | '/m/$merchantId/campaigns/list'
    | '/m/$merchantId/campaigns/overview'
    | '/m/$merchantId/merchant/customize'
    | '/m/$merchantId/merchant/funding'
    | '/m/$merchantId/merchant/setup-status'
    | '/m/$merchantId/merchant/team'
    | '/m/$merchantId/push/confirm'
    | '/m/$merchantId/push/create'
    | '/campaigns/draft/$campaignId/'
    | '/m/$merchantId/merchant/'
    | '/m/$merchantId/campaigns/draft/new'
    | '/m/$merchantId/campaigns/edit/$campaignId'
    | '/m/$merchantId/campaigns/draft/$campaignId/metrics'
    | '/m/$merchantId/campaigns/draft/$campaignId/validation'
    | '/m/$merchantId/campaigns/draft/$campaignId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/dashboard'
    | '/members'
    | '/settings'
    | '/embedded'
    | '/embedded/auth'
    | '/campaigns/$campaignId'
    | '/campaigns/list'
    | '/campaigns/overview'
    | '/m/$merchantId'
    | '/push/confirm'
    | '/push/create'
    | '/embedded/mint'
    | '/campaigns/draft/new'
    | '/campaigns/edit/$campaignId'
    | '/m/$merchantId/dashboard'
    | '/m/$merchantId/members'
    | '/merchant/$id/customize'
    | '/merchant/$id/funding'
    | '/merchant/$id/setup-status'
    | '/merchant/$id/team'
    | '/merchant/$id'
    | '/campaigns/draft/$campaignId/metrics'
    | '/campaigns/draft/$campaignId/validation'
    | '/m/$merchantId/campaigns/$campaignId'
    | '/m/$merchantId/campaigns/list'
    | '/m/$merchantId/campaigns/overview'
    | '/m/$merchantId/merchant/customize'
    | '/m/$merchantId/merchant/funding'
    | '/m/$merchantId/merchant/setup-status'
    | '/m/$merchantId/merchant/team'
    | '/m/$merchantId/push/confirm'
    | '/m/$merchantId/push/create'
    | '/campaigns/draft/$campaignId'
    | '/m/$merchantId/merchant'
    | '/m/$merchantId/campaigns/draft/new'
    | '/m/$merchantId/campaigns/edit/$campaignId'
    | '/m/$merchantId/campaigns/draft/$campaignId/metrics'
    | '/m/$merchantId/campaigns/draft/$campaignId/validation'
    | '/m/$merchantId/campaigns/draft/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/_restricted'
    | '/demo'
    | '/login'
    | '/_restricted/dashboard'
    | '/_restricted/members'
    | '/_restricted/settings'
    | '/embedded/_layout'
    | '/embedded/auth'
    | '/_restricted/campaigns/$campaignId'
    | '/_restricted/campaigns/list'
    | '/_restricted/campaigns/overview'
    | '/_restricted/m/$merchantId'
    | '/_restricted/push/confirm'
    | '/_restricted/push/create'
    | '/embedded/_layout/mint'
    | '/_restricted/campaigns/draft/new'
    | '/_restricted/campaigns/edit/$campaignId'
    | '/_restricted/m/$merchantId/dashboard'
    | '/_restricted/m/$merchantId/members'
    | '/_restricted/merchant/$id/customize'
    | '/_restricted/merchant/$id/funding'
    | '/_restricted/merchant/$id/setup-status'
    | '/_restricted/merchant/$id/team'
    | '/_restricted/merchant/$id/'
    | '/_restricted/campaigns/draft/$campaignId/metrics'
    | '/_restricted/campaigns/draft/$campaignId/validation'
    | '/_restricted/m/$merchantId/campaigns/$campaignId'
    | '/_restricted/m/$merchantId/campaigns/list'
    | '/_restricted/m/$merchantId/campaigns/overview'
    | '/_restricted/m/$merchantId/merchant/customize'
    | '/_restricted/m/$merchantId/merchant/funding'
    | '/_restricted/m/$merchantId/merchant/setup-status'
    | '/_restricted/m/$merchantId/merchant/team'
    | '/_restricted/m/$merchantId/push/confirm'
    | '/_restricted/m/$merchantId/push/create'
    | '/_restricted/campaigns/draft/$campaignId/'
    | '/_restricted/m/$merchantId/merchant/'
    | '/_restricted/m/$merchantId/campaigns/draft/new'
    | '/_restricted/m/$merchantId/campaigns/edit/$campaignId'
    | '/_restricted/m/$merchantId/campaigns/draft/$campaignId/metrics'
    | '/_restricted/m/$merchantId/campaigns/draft/$campaignId/validation'
    | '/_restricted/m/$merchantId/campaigns/draft/$campaignId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestrictedRoute: typeof RestrictedRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  EmbeddedLayoutRoute: typeof EmbeddedLayoutRouteWithChildren
  EmbeddedAuthRoute: typeof EmbeddedAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_restricted': {
      id: '/_restricted'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embedded/auth': {
      id: '/embedded/auth'
      path: '/embedded/auth'
      fullPath: '/embedded/auth'
      preLoaderRoute: typeof EmbeddedAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embedded/_layout': {
      id: '/embedded/_layout'
      path: '/embedded'
      fullPath: '/embedded'
      preLoaderRoute: typeof EmbeddedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_restricted/settings': {
      id: '/_restricted/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof RestrictedSettingsRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/members': {
      id: '/_restricted/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof RestrictedMembersRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/dashboard': {
      id: '/_restricted/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof RestrictedDashboardRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/embedded/_layout/mint': {
      id: '/embedded/_layout/mint'
      path: '/mint'
      fullPath: '/embedded/mint'
      preLoaderRoute: typeof EmbeddedLayoutMintRouteImport
      parentRoute: typeof EmbeddedLayoutRoute
    }
    '/_restricted/push/create': {
      id: '/_restricted/push/create'
      path: '/push/create'
      fullPath: '/push/create'
      preLoaderRoute: typeof RestrictedPushCreateRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/push/confirm': {
      id: '/_restricted/push/confirm'
      path: '/push/confirm'
      fullPath: '/push/confirm'
      preLoaderRoute: typeof RestrictedPushConfirmRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/m/$merchantId': {
      id: '/_restricted/m/$merchantId'
      path: '/m/$merchantId'
      fullPath: '/m/$merchantId'
      preLoaderRoute: typeof RestrictedMMerchantIdRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/overview': {
      id: '/_restricted/campaigns/overview'
      path: '/campaigns/overview'
      fullPath: '/campaigns/overview'
      preLoaderRoute: typeof RestrictedCampaignsOverviewRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/list': {
      id: '/_restricted/campaigns/list'
      path: '/campaigns/list'
      fullPath: '/campaigns/list'
      preLoaderRoute: typeof RestrictedCampaignsListRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/$campaignId': {
      id: '/_restricted/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof RestrictedCampaignsCampaignIdRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/merchant/$id/': {
      id: '/_restricted/merchant/$id/'
      path: '/merchant/$id'
      fullPath: '/merchant/$id/'
      preLoaderRoute: typeof RestrictedMerchantIdIndexRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/merchant/$id/team': {
      id: '/_restricted/merchant/$id/team'
      path: '/merchant/$id/team'
      fullPath: '/merchant/$id/team'
      preLoaderRoute: typeof RestrictedMerchantIdTeamRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/merchant/$id/setup-status': {
      id: '/_restricted/merchant/$id/setup-status'
      path: '/merchant/$id/setup-status'
      fullPath: '/merchant/$id/setup-status'
      preLoaderRoute: typeof RestrictedMerchantIdSetupStatusRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/merchant/$id/funding': {
      id: '/_restricted/merchant/$id/funding'
      path: '/merchant/$id/funding'
      fullPath: '/merchant/$id/funding'
      preLoaderRoute: typeof RestrictedMerchantIdFundingRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/merchant/$id/customize': {
      id: '/_restricted/merchant/$id/customize'
      path: '/merchant/$id/customize'
      fullPath: '/merchant/$id/customize'
      preLoaderRoute: typeof RestrictedMerchantIdCustomizeRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/m/$merchantId/members': {
      id: '/_restricted/m/$merchantId/members'
      path: '/members'
      fullPath: '/m/$merchantId/members'
      preLoaderRoute: typeof RestrictedMMerchantIdMembersRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/dashboard': {
      id: '/_restricted/m/$merchantId/dashboard'
      path: '/dashboard'
      fullPath: '/m/$merchantId/dashboard'
      preLoaderRoute: typeof RestrictedMMerchantIdDashboardRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/campaigns/edit/$campaignId': {
      id: '/_restricted/campaigns/edit/$campaignId'
      path: '/campaigns/edit/$campaignId'
      fullPath: '/campaigns/edit/$campaignId'
      preLoaderRoute: typeof RestrictedCampaignsEditCampaignIdRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/draft/new': {
      id: '/_restricted/campaigns/draft/new'
      path: '/campaigns/draft/new'
      fullPath: '/campaigns/draft/new'
      preLoaderRoute: typeof RestrictedCampaignsDraftNewRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/m/$merchantId/merchant/': {
      id: '/_restricted/m/$merchantId/merchant/'
      path: '/merchant'
      fullPath: '/m/$merchantId/merchant/'
      preLoaderRoute: typeof RestrictedMMerchantIdMerchantIndexRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/campaigns/draft/$campaignId/': {
      id: '/_restricted/campaigns/draft/$campaignId/'
      path: '/campaigns/draft/$campaignId'
      fullPath: '/campaigns/draft/$campaignId/'
      preLoaderRoute: typeof RestrictedCampaignsDraftCampaignIdIndexRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/m/$merchantId/push/create': {
      id: '/_restricted/m/$merchantId/push/create'
      path: '/push/create'
      fullPath: '/m/$merchantId/push/create'
      preLoaderRoute: typeof RestrictedMMerchantIdPushCreateRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/push/confirm': {
      id: '/_restricted/m/$merchantId/push/confirm'
      path: '/push/confirm'
      fullPath: '/m/$merchantId/push/confirm'
      preLoaderRoute: typeof RestrictedMMerchantIdPushConfirmRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/merchant/team': {
      id: '/_restricted/m/$merchantId/merchant/team'
      path: '/merchant/team'
      fullPath: '/m/$merchantId/merchant/team'
      preLoaderRoute: typeof RestrictedMMerchantIdMerchantTeamRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/merchant/setup-status': {
      id: '/_restricted/m/$merchantId/merchant/setup-status'
      path: '/merchant/setup-status'
      fullPath: '/m/$merchantId/merchant/setup-status'
      preLoaderRoute: typeof RestrictedMMerchantIdMerchantSetupStatusRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/merchant/funding': {
      id: '/_restricted/m/$merchantId/merchant/funding'
      path: '/merchant/funding'
      fullPath: '/m/$merchantId/merchant/funding'
      preLoaderRoute: typeof RestrictedMMerchantIdMerchantFundingRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/merchant/customize': {
      id: '/_restricted/m/$merchantId/merchant/customize'
      path: '/merchant/customize'
      fullPath: '/m/$merchantId/merchant/customize'
      preLoaderRoute: typeof RestrictedMMerchantIdMerchantCustomizeRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/campaigns/overview': {
      id: '/_restricted/m/$merchantId/campaigns/overview'
      path: '/campaigns/overview'
      fullPath: '/m/$merchantId/campaigns/overview'
      preLoaderRoute: typeof RestrictedMMerchantIdCampaignsOverviewRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/campaigns/list': {
      id: '/_restricted/m/$merchantId/campaigns/list'
      path: '/campaigns/list'
      fullPath: '/m/$merchantId/campaigns/list'
      preLoaderRoute: typeof RestrictedMMerchantIdCampaignsListRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/campaigns/$campaignId': {
      id: '/_restricted/m/$merchantId/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/m/$merchantId/campaigns/$campaignId'
      preLoaderRoute: typeof RestrictedMMerchantIdCampaignsCampaignIdRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/campaigns/draft/$campaignId/validation': {
      id: '/_restricted/campaigns/draft/$campaignId/validation'
      path: '/campaigns/draft/$campaignId/validation'
      fullPath: '/campaigns/draft/$campaignId/validation'
      preLoaderRoute: typeof RestrictedCampaignsDraftCampaignIdValidationRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/draft/$campaignId/metrics': {
      id: '/_restricted/campaigns/draft/$campaignId/metrics'
      path: '/campaigns/draft/$campaignId/metrics'
      fullPath: '/campaigns/draft/$campaignId/metrics'
      preLoaderRoute: typeof RestrictedCampaignsDraftCampaignIdMetricsRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/m/$merchantId/campaigns/edit/$campaignId': {
      id: '/_restricted/m/$merchantId/campaigns/edit/$campaignId'
      path: '/campaigns/edit/$campaignId'
      fullPath: '/m/$merchantId/campaigns/edit/$campaignId'
      preLoaderRoute: typeof RestrictedMMerchantIdCampaignsEditCampaignIdRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/campaigns/draft/new': {
      id: '/_restricted/m/$merchantId/campaigns/draft/new'
      path: '/campaigns/draft/new'
      fullPath: '/m/$merchantId/campaigns/draft/new'
      preLoaderRoute: typeof RestrictedMMerchantIdCampaignsDraftNewRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/campaigns/draft/$campaignId/': {
      id: '/_restricted/m/$merchantId/campaigns/draft/$campaignId/'
      path: '/campaigns/draft/$campaignId'
      fullPath: '/m/$merchantId/campaigns/draft/$campaignId/'
      preLoaderRoute: typeof RestrictedMMerchantIdCampaignsDraftCampaignIdIndexRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/campaigns/draft/$campaignId/validation': {
      id: '/_restricted/m/$merchantId/campaigns/draft/$campaignId/validation'
      path: '/campaigns/draft/$campaignId/validation'
      fullPath: '/m/$merchantId/campaigns/draft/$campaignId/validation'
      preLoaderRoute: typeof RestrictedMMerchantIdCampaignsDraftCampaignIdValidationRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
    '/_restricted/m/$merchantId/campaigns/draft/$campaignId/metrics': {
      id: '/_restricted/m/$merchantId/campaigns/draft/$campaignId/metrics'
      path: '/campaigns/draft/$campaignId/metrics'
      fullPath: '/m/$merchantId/campaigns/draft/$campaignId/metrics'
      preLoaderRoute: typeof RestrictedMMerchantIdCampaignsDraftCampaignIdMetricsRouteImport
      parentRoute: typeof RestrictedMMerchantIdRoute
    }
  }
}

interface RestrictedMMerchantIdRouteChildren {
  RestrictedMMerchantIdDashboardRoute: typeof RestrictedMMerchantIdDashboardRoute
  RestrictedMMerchantIdMembersRoute: typeof RestrictedMMerchantIdMembersRoute
  RestrictedMMerchantIdCampaignsCampaignIdRoute: typeof RestrictedMMerchantIdCampaignsCampaignIdRoute
  RestrictedMMerchantIdCampaignsListRoute: typeof RestrictedMMerchantIdCampaignsListRoute
  RestrictedMMerchantIdCampaignsOverviewRoute: typeof RestrictedMMerchantIdCampaignsOverviewRoute
  RestrictedMMerchantIdMerchantCustomizeRoute: typeof RestrictedMMerchantIdMerchantCustomizeRoute
  RestrictedMMerchantIdMerchantFundingRoute: typeof RestrictedMMerchantIdMerchantFundingRoute
  RestrictedMMerchantIdMerchantSetupStatusRoute: typeof RestrictedMMerchantIdMerchantSetupStatusRoute
  RestrictedMMerchantIdMerchantTeamRoute: typeof RestrictedMMerchantIdMerchantTeamRoute
  RestrictedMMerchantIdPushConfirmRoute: typeof RestrictedMMerchantIdPushConfirmRoute
  RestrictedMMerchantIdPushCreateRoute: typeof RestrictedMMerchantIdPushCreateRoute
  RestrictedMMerchantIdMerchantIndexRoute: typeof RestrictedMMerchantIdMerchantIndexRoute
  RestrictedMMerchantIdCampaignsDraftNewRoute: typeof RestrictedMMerchantIdCampaignsDraftNewRoute
  RestrictedMMerchantIdCampaignsEditCampaignIdRoute: typeof RestrictedMMerchantIdCampaignsEditCampaignIdRoute
  RestrictedMMerchantIdCampaignsDraftCampaignIdMetricsRoute: typeof RestrictedMMerchantIdCampaignsDraftCampaignIdMetricsRoute
  RestrictedMMerchantIdCampaignsDraftCampaignIdValidationRoute: typeof RestrictedMMerchantIdCampaignsDraftCampaignIdValidationRoute
  RestrictedMMerchantIdCampaignsDraftCampaignIdIndexRoute: typeof RestrictedMMerchantIdCampaignsDraftCampaignIdIndexRoute
}

const RestrictedMMerchantIdRouteChildren: RestrictedMMerchantIdRouteChildren = {
  RestrictedMMerchantIdDashboardRoute: RestrictedMMerchantIdDashboardRoute,
  RestrictedMMerchantIdMembersRoute: RestrictedMMerchantIdMembersRoute,
  RestrictedMMerchantIdCampaignsCampaignIdRoute:
    RestrictedMMerchantIdCampaignsCampaignIdRoute,
  RestrictedMMerchantIdCampaignsListRoute:
    RestrictedMMerchantIdCampaignsListRoute,
  RestrictedMMerchantIdCampaignsOverviewRoute:
    RestrictedMMerchantIdCampaignsOverviewRoute,
  RestrictedMMerchantIdMerchantCustomizeRoute:
    RestrictedMMerchantIdMerchantCustomizeRoute,
  RestrictedMMerchantIdMerchantFundingRoute:
    RestrictedMMerchantIdMerchantFundingRoute,
  RestrictedMMerchantIdMerchantSetupStatusRoute:
    RestrictedMMerchantIdMerchantSetupStatusRoute,
  RestrictedMMerchantIdMerchantTeamRoute:
    RestrictedMMerchantIdMerchantTeamRoute,
  RestrictedMMerchantIdPushConfirmRoute: RestrictedMMerchantIdPushConfirmRoute,
  RestrictedMMerchantIdPushCreateRoute: RestrictedMMerchantIdPushCreateRoute,
  RestrictedMMerchantIdMerchantIndexRoute:
    RestrictedMMerchantIdMerchantIndexRoute,
  RestrictedMMerchantIdCampaignsDraftNewRoute:
    RestrictedMMerchantIdCampaignsDraftNewRoute,
  RestrictedMMerchantIdCampaignsEditCampaignIdRoute:
    RestrictedMMerchantIdCampaignsEditCampaignIdRoute,
  RestrictedMMerchantIdCampaignsDraftCampaignIdMetricsRoute:
    RestrictedMMerchantIdCampaignsDraftCampaignIdMetricsRoute,
  RestrictedMMerchantIdCampaignsDraftCampaignIdValidationRoute:
    RestrictedMMerchantIdCampaignsDraftCampaignIdValidationRoute,
  RestrictedMMerchantIdCampaignsDraftCampaignIdIndexRoute:
    RestrictedMMerchantIdCampaignsDraftCampaignIdIndexRoute,
}

const RestrictedMMerchantIdRouteWithChildren =
  RestrictedMMerchantIdRoute._addFileChildren(
    RestrictedMMerchantIdRouteChildren,
  )

interface RestrictedRouteChildren {
  RestrictedDashboardRoute: typeof RestrictedDashboardRoute
  RestrictedMembersRoute: typeof RestrictedMembersRoute
  RestrictedSettingsRoute: typeof RestrictedSettingsRoute
  RestrictedCampaignsCampaignIdRoute: typeof RestrictedCampaignsCampaignIdRoute
  RestrictedCampaignsListRoute: typeof RestrictedCampaignsListRoute
  RestrictedCampaignsOverviewRoute: typeof RestrictedCampaignsOverviewRoute
  RestrictedMMerchantIdRoute: typeof RestrictedMMerchantIdRouteWithChildren
  RestrictedPushConfirmRoute: typeof RestrictedPushConfirmRoute
  RestrictedPushCreateRoute: typeof RestrictedPushCreateRoute
  RestrictedCampaignsDraftNewRoute: typeof RestrictedCampaignsDraftNewRoute
  RestrictedCampaignsEditCampaignIdRoute: typeof RestrictedCampaignsEditCampaignIdRoute
  RestrictedMerchantIdCustomizeRoute: typeof RestrictedMerchantIdCustomizeRoute
  RestrictedMerchantIdFundingRoute: typeof RestrictedMerchantIdFundingRoute
  RestrictedMerchantIdSetupStatusRoute: typeof RestrictedMerchantIdSetupStatusRoute
  RestrictedMerchantIdTeamRoute: typeof RestrictedMerchantIdTeamRoute
  RestrictedMerchantIdIndexRoute: typeof RestrictedMerchantIdIndexRoute
  RestrictedCampaignsDraftCampaignIdMetricsRoute: typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  RestrictedCampaignsDraftCampaignIdValidationRoute: typeof RestrictedCampaignsDraftCampaignIdValidationRoute
  RestrictedCampaignsDraftCampaignIdIndexRoute: typeof RestrictedCampaignsDraftCampaignIdIndexRoute
}

const RestrictedRouteChildren: RestrictedRouteChildren = {
  RestrictedDashboardRoute: RestrictedDashboardRoute,
  RestrictedMembersRoute: RestrictedMembersRoute,
  RestrictedSettingsRoute: RestrictedSettingsRoute,
  RestrictedCampaignsCampaignIdRoute: RestrictedCampaignsCampaignIdRoute,
  RestrictedCampaignsListRoute: RestrictedCampaignsListRoute,
  RestrictedCampaignsOverviewRoute: RestrictedCampaignsOverviewRoute,
  RestrictedMMerchantIdRoute: RestrictedMMerchantIdRouteWithChildren,
  RestrictedPushConfirmRoute: RestrictedPushConfirmRoute,
  RestrictedPushCreateRoute: RestrictedPushCreateRoute,
  RestrictedCampaignsDraftNewRoute: RestrictedCampaignsDraftNewRoute,
  RestrictedCampaignsEditCampaignIdRoute:
    RestrictedCampaignsEditCampaignIdRoute,
  RestrictedMerchantIdCustomizeRoute: RestrictedMerchantIdCustomizeRoute,
  RestrictedMerchantIdFundingRoute: RestrictedMerchantIdFundingRoute,
  RestrictedMerchantIdSetupStatusRoute: RestrictedMerchantIdSetupStatusRoute,
  RestrictedMerchantIdTeamRoute: RestrictedMerchantIdTeamRoute,
  RestrictedMerchantIdIndexRoute: RestrictedMerchantIdIndexRoute,
  RestrictedCampaignsDraftCampaignIdMetricsRoute:
    RestrictedCampaignsDraftCampaignIdMetricsRoute,
  RestrictedCampaignsDraftCampaignIdValidationRoute:
    RestrictedCampaignsDraftCampaignIdValidationRoute,
  RestrictedCampaignsDraftCampaignIdIndexRoute:
    RestrictedCampaignsDraftCampaignIdIndexRoute,
}

const RestrictedRouteWithChildren = RestrictedRoute._addFileChildren(
  RestrictedRouteChildren,
)

interface EmbeddedLayoutRouteChildren {
  EmbeddedLayoutMintRoute: typeof EmbeddedLayoutMintRoute
}

const EmbeddedLayoutRouteChildren: EmbeddedLayoutRouteChildren = {
  EmbeddedLayoutMintRoute: EmbeddedLayoutMintRoute,
}

const EmbeddedLayoutRouteWithChildren = EmbeddedLayoutRoute._addFileChildren(
  EmbeddedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestrictedRoute: RestrictedRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  EmbeddedLayoutRoute: EmbeddedLayoutRouteWithChildren,
  EmbeddedAuthRoute: EmbeddedAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
