/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as RestrictedRouteImport } from './routes/_restricted'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbeddedLayoutRouteImport } from './routes/embedded/_layout'
import { Route as RestrictedSettingsRouteImport } from './routes/_restricted/settings'
import { Route as RestrictedMintRouteImport } from './routes/_restricted/mint'
import { Route as RestrictedMembersRouteImport } from './routes/_restricted/members'
import { Route as RestrictedDashboardRouteImport } from './routes/_restricted/dashboard'
import { Route as EmbeddedLayoutPurchaseTrackerRouteImport } from './routes/embedded/_layout/purchase-tracker'
import { Route as EmbeddedLayoutMintRouteImport } from './routes/embedded/_layout/mint'
import { Route as EmbeddedLayoutCreateCampaignRouteImport } from './routes/embedded/_layout/create-campaign'
import { Route as RestrictedPushCreateRouteImport } from './routes/_restricted/push/create'
import { Route as RestrictedPushConfirmRouteImport } from './routes/_restricted/push/confirm'
import { Route as RestrictedCampaignsValidationRouteImport } from './routes/_restricted/campaigns/validation'
import { Route as RestrictedCampaignsPerformanceRouteImport } from './routes/_restricted/campaigns/performance'
import { Route as RestrictedCampaignsNewRouteImport } from './routes/_restricted/campaigns/new'
import { Route as RestrictedCampaignsMetricsRouteImport } from './routes/_restricted/campaigns/metrics'
import { Route as RestrictedCampaignsListRouteImport } from './routes/_restricted/campaigns/list'
import { Route as RestrictedCampaignsCampaignIdRouteImport } from './routes/_restricted/campaigns/$campaignId'
import { Route as RestrictedProductIdIndexRouteImport } from './routes/_restricted/product/$id/index'
import { Route as RestrictedProductIdTeamRouteImport } from './routes/_restricted/product/$id/team'
import { Route as RestrictedProductIdSetupStatusRouteImport } from './routes/_restricted/product/$id/setup-status'
import { Route as RestrictedProductIdFundingRouteImport } from './routes/_restricted/product/$id/funding'
import { Route as RestrictedCampaignsEditCampaignIdRouteImport } from './routes/_restricted/campaigns/edit/$campaignId'
import { Route as RestrictedCampaignsDraftCampaignIdRouteImport } from './routes/_restricted/campaigns/draft/$campaignId'
import { Route as RestrictedCampaignsDraftCampaignIdValidationRouteImport } from './routes/_restricted/campaigns/draft/$campaignId/validation'
import { Route as RestrictedCampaignsDraftCampaignIdMetricsRouteImport } from './routes/_restricted/campaigns/draft/$campaignId/metrics'

const EmbeddedRouteImport = createFileRoute('/embedded')()

const EmbeddedRoute = EmbeddedRouteImport.update({
  id: '/embedded',
  path: '/embedded',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const RestrictedRoute = RestrictedRouteImport.update({
  id: '/_restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddedLayoutRoute = EmbeddedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => EmbeddedRoute,
} as any)
const RestrictedSettingsRoute = RestrictedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedMintRoute = RestrictedMintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedMembersRoute = RestrictedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedDashboardRoute = RestrictedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RestrictedRoute,
} as any)
const EmbeddedLayoutPurchaseTrackerRoute =
  EmbeddedLayoutPurchaseTrackerRouteImport.update({
    id: '/purchase-tracker',
    path: '/purchase-tracker',
    getParentRoute: () => EmbeddedLayoutRoute,
  } as any)
const EmbeddedLayoutMintRoute = EmbeddedLayoutMintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => EmbeddedLayoutRoute,
} as any)
const EmbeddedLayoutCreateCampaignRoute =
  EmbeddedLayoutCreateCampaignRouteImport.update({
    id: '/create-campaign',
    path: '/create-campaign',
    getParentRoute: () => EmbeddedLayoutRoute,
  } as any)
const RestrictedPushCreateRoute = RestrictedPushCreateRouteImport.update({
  id: '/push/create',
  path: '/push/create',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedPushConfirmRoute = RestrictedPushConfirmRouteImport.update({
  id: '/push/confirm',
  path: '/push/confirm',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedCampaignsValidationRoute =
  RestrictedCampaignsValidationRouteImport.update({
    id: '/campaigns/validation',
    path: '/campaigns/validation',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsPerformanceRoute =
  RestrictedCampaignsPerformanceRouteImport.update({
    id: '/campaigns/performance',
    path: '/campaigns/performance',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsNewRoute = RestrictedCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedCampaignsMetricsRoute =
  RestrictedCampaignsMetricsRouteImport.update({
    id: '/campaigns/metrics',
    path: '/campaigns/metrics',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsListRoute = RestrictedCampaignsListRouteImport.update({
  id: '/campaigns/list',
  path: '/campaigns/list',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedCampaignsCampaignIdRoute =
  RestrictedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedProductIdIndexRoute =
  RestrictedProductIdIndexRouteImport.update({
    id: '/product/$id/',
    path: '/product/$id/',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedProductIdTeamRoute = RestrictedProductIdTeamRouteImport.update({
  id: '/product/$id/team',
  path: '/product/$id/team',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedProductIdSetupStatusRoute =
  RestrictedProductIdSetupStatusRouteImport.update({
    id: '/product/$id/setup-status',
    path: '/product/$id/setup-status',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedProductIdFundingRoute =
  RestrictedProductIdFundingRouteImport.update({
    id: '/product/$id/funding',
    path: '/product/$id/funding',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsEditCampaignIdRoute =
  RestrictedCampaignsEditCampaignIdRouteImport.update({
    id: '/campaigns/edit/$campaignId',
    path: '/campaigns/edit/$campaignId',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsDraftCampaignIdRoute =
  RestrictedCampaignsDraftCampaignIdRouteImport.update({
    id: '/campaigns/draft/$campaignId',
    path: '/campaigns/draft/$campaignId',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsDraftCampaignIdValidationRoute =
  RestrictedCampaignsDraftCampaignIdValidationRouteImport.update({
    id: '/validation',
    path: '/validation',
    getParentRoute: () => RestrictedCampaignsDraftCampaignIdRoute,
  } as any)
const RestrictedCampaignsDraftCampaignIdMetricsRoute =
  RestrictedCampaignsDraftCampaignIdMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => RestrictedCampaignsDraftCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/dashboard': typeof RestrictedDashboardRoute
  '/members': typeof RestrictedMembersRoute
  '/mint': typeof RestrictedMintRoute
  '/settings': typeof RestrictedSettingsRoute
  '/embedded': typeof EmbeddedLayoutRouteWithChildren
  '/campaigns/$campaignId': typeof RestrictedCampaignsCampaignIdRoute
  '/campaigns/list': typeof RestrictedCampaignsListRoute
  '/campaigns/metrics': typeof RestrictedCampaignsMetricsRoute
  '/campaigns/new': typeof RestrictedCampaignsNewRoute
  '/campaigns/performance': typeof RestrictedCampaignsPerformanceRoute
  '/campaigns/validation': typeof RestrictedCampaignsValidationRoute
  '/push/confirm': typeof RestrictedPushConfirmRoute
  '/push/create': typeof RestrictedPushCreateRoute
  '/embedded/create-campaign': typeof EmbeddedLayoutCreateCampaignRoute
  '/embedded/mint': typeof EmbeddedLayoutMintRoute
  '/embedded/purchase-tracker': typeof EmbeddedLayoutPurchaseTrackerRoute
  '/campaigns/draft/$campaignId': typeof RestrictedCampaignsDraftCampaignIdRouteWithChildren
  '/campaigns/edit/$campaignId': typeof RestrictedCampaignsEditCampaignIdRoute
  '/product/$id/funding': typeof RestrictedProductIdFundingRoute
  '/product/$id/setup-status': typeof RestrictedProductIdSetupStatusRoute
  '/product/$id/team': typeof RestrictedProductIdTeamRoute
  '/product/$id': typeof RestrictedProductIdIndexRoute
  '/campaigns/draft/$campaignId/metrics': typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  '/campaigns/draft/$campaignId/validation': typeof RestrictedCampaignsDraftCampaignIdValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/dashboard': typeof RestrictedDashboardRoute
  '/members': typeof RestrictedMembersRoute
  '/mint': typeof RestrictedMintRoute
  '/settings': typeof RestrictedSettingsRoute
  '/embedded': typeof EmbeddedLayoutRouteWithChildren
  '/campaigns/$campaignId': typeof RestrictedCampaignsCampaignIdRoute
  '/campaigns/list': typeof RestrictedCampaignsListRoute
  '/campaigns/metrics': typeof RestrictedCampaignsMetricsRoute
  '/campaigns/new': typeof RestrictedCampaignsNewRoute
  '/campaigns/performance': typeof RestrictedCampaignsPerformanceRoute
  '/campaigns/validation': typeof RestrictedCampaignsValidationRoute
  '/push/confirm': typeof RestrictedPushConfirmRoute
  '/push/create': typeof RestrictedPushCreateRoute
  '/embedded/create-campaign': typeof EmbeddedLayoutCreateCampaignRoute
  '/embedded/mint': typeof EmbeddedLayoutMintRoute
  '/embedded/purchase-tracker': typeof EmbeddedLayoutPurchaseTrackerRoute
  '/campaigns/draft/$campaignId': typeof RestrictedCampaignsDraftCampaignIdRouteWithChildren
  '/campaigns/edit/$campaignId': typeof RestrictedCampaignsEditCampaignIdRoute
  '/product/$id/funding': typeof RestrictedProductIdFundingRoute
  '/product/$id/setup-status': typeof RestrictedProductIdSetupStatusRoute
  '/product/$id/team': typeof RestrictedProductIdTeamRoute
  '/product/$id': typeof RestrictedProductIdIndexRoute
  '/campaigns/draft/$campaignId/metrics': typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  '/campaigns/draft/$campaignId/validation': typeof RestrictedCampaignsDraftCampaignIdValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_restricted': typeof RestrictedRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/_restricted/dashboard': typeof RestrictedDashboardRoute
  '/_restricted/members': typeof RestrictedMembersRoute
  '/_restricted/mint': typeof RestrictedMintRoute
  '/_restricted/settings': typeof RestrictedSettingsRoute
  '/embedded': typeof EmbeddedRouteWithChildren
  '/embedded/_layout': typeof EmbeddedLayoutRouteWithChildren
  '/_restricted/campaigns/$campaignId': typeof RestrictedCampaignsCampaignIdRoute
  '/_restricted/campaigns/list': typeof RestrictedCampaignsListRoute
  '/_restricted/campaigns/metrics': typeof RestrictedCampaignsMetricsRoute
  '/_restricted/campaigns/new': typeof RestrictedCampaignsNewRoute
  '/_restricted/campaigns/performance': typeof RestrictedCampaignsPerformanceRoute
  '/_restricted/campaigns/validation': typeof RestrictedCampaignsValidationRoute
  '/_restricted/push/confirm': typeof RestrictedPushConfirmRoute
  '/_restricted/push/create': typeof RestrictedPushCreateRoute
  '/embedded/_layout/create-campaign': typeof EmbeddedLayoutCreateCampaignRoute
  '/embedded/_layout/mint': typeof EmbeddedLayoutMintRoute
  '/embedded/_layout/purchase-tracker': typeof EmbeddedLayoutPurchaseTrackerRoute
  '/_restricted/campaigns/draft/$campaignId': typeof RestrictedCampaignsDraftCampaignIdRouteWithChildren
  '/_restricted/campaigns/edit/$campaignId': typeof RestrictedCampaignsEditCampaignIdRoute
  '/_restricted/product/$id/funding': typeof RestrictedProductIdFundingRoute
  '/_restricted/product/$id/setup-status': typeof RestrictedProductIdSetupStatusRoute
  '/_restricted/product/$id/team': typeof RestrictedProductIdTeamRoute
  '/_restricted/product/$id/': typeof RestrictedProductIdIndexRoute
  '/_restricted/campaigns/draft/$campaignId/metrics': typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  '/_restricted/campaigns/draft/$campaignId/validation': typeof RestrictedCampaignsDraftCampaignIdValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/not-found'
    | '/dashboard'
    | '/members'
    | '/mint'
    | '/settings'
    | '/embedded'
    | '/campaigns/$campaignId'
    | '/campaigns/list'
    | '/campaigns/metrics'
    | '/campaigns/new'
    | '/campaigns/performance'
    | '/campaigns/validation'
    | '/push/confirm'
    | '/push/create'
    | '/embedded/create-campaign'
    | '/embedded/mint'
    | '/embedded/purchase-tracker'
    | '/campaigns/draft/$campaignId'
    | '/campaigns/edit/$campaignId'
    | '/product/$id/funding'
    | '/product/$id/setup-status'
    | '/product/$id/team'
    | '/product/$id'
    | '/campaigns/draft/$campaignId/metrics'
    | '/campaigns/draft/$campaignId/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/not-found'
    | '/dashboard'
    | '/members'
    | '/mint'
    | '/settings'
    | '/embedded'
    | '/campaigns/$campaignId'
    | '/campaigns/list'
    | '/campaigns/metrics'
    | '/campaigns/new'
    | '/campaigns/performance'
    | '/campaigns/validation'
    | '/push/confirm'
    | '/push/create'
    | '/embedded/create-campaign'
    | '/embedded/mint'
    | '/embedded/purchase-tracker'
    | '/campaigns/draft/$campaignId'
    | '/campaigns/edit/$campaignId'
    | '/product/$id/funding'
    | '/product/$id/setup-status'
    | '/product/$id/team'
    | '/product/$id'
    | '/campaigns/draft/$campaignId/metrics'
    | '/campaigns/draft/$campaignId/validation'
  id:
    | '__root__'
    | '/'
    | '/_restricted'
    | '/demo'
    | '/login'
    | '/not-found'
    | '/_restricted/dashboard'
    | '/_restricted/members'
    | '/_restricted/mint'
    | '/_restricted/settings'
    | '/embedded'
    | '/embedded/_layout'
    | '/_restricted/campaigns/$campaignId'
    | '/_restricted/campaigns/list'
    | '/_restricted/campaigns/metrics'
    | '/_restricted/campaigns/new'
    | '/_restricted/campaigns/performance'
    | '/_restricted/campaigns/validation'
    | '/_restricted/push/confirm'
    | '/_restricted/push/create'
    | '/embedded/_layout/create-campaign'
    | '/embedded/_layout/mint'
    | '/embedded/_layout/purchase-tracker'
    | '/_restricted/campaigns/draft/$campaignId'
    | '/_restricted/campaigns/edit/$campaignId'
    | '/_restricted/product/$id/funding'
    | '/_restricted/product/$id/setup-status'
    | '/_restricted/product/$id/team'
    | '/_restricted/product/$id/'
    | '/_restricted/campaigns/draft/$campaignId/metrics'
    | '/_restricted/campaigns/draft/$campaignId/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestrictedRoute: typeof RestrictedRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  EmbeddedRoute: typeof EmbeddedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/embedded': {
      id: '/embedded'
      path: '/embedded'
      fullPath: '/embedded'
      preLoaderRoute: typeof EmbeddedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_restricted': {
      id: '/_restricted'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embedded/_layout': {
      id: '/embedded/_layout'
      path: '/embedded'
      fullPath: '/embedded'
      preLoaderRoute: typeof EmbeddedLayoutRouteImport
      parentRoute: typeof EmbeddedRoute
    }
    '/_restricted/settings': {
      id: '/_restricted/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof RestrictedSettingsRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/mint': {
      id: '/_restricted/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof RestrictedMintRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/members': {
      id: '/_restricted/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof RestrictedMembersRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/dashboard': {
      id: '/_restricted/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof RestrictedDashboardRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/embedded/_layout/purchase-tracker': {
      id: '/embedded/_layout/purchase-tracker'
      path: '/purchase-tracker'
      fullPath: '/embedded/purchase-tracker'
      preLoaderRoute: typeof EmbeddedLayoutPurchaseTrackerRouteImport
      parentRoute: typeof EmbeddedLayoutRoute
    }
    '/embedded/_layout/mint': {
      id: '/embedded/_layout/mint'
      path: '/mint'
      fullPath: '/embedded/mint'
      preLoaderRoute: typeof EmbeddedLayoutMintRouteImport
      parentRoute: typeof EmbeddedLayoutRoute
    }
    '/embedded/_layout/create-campaign': {
      id: '/embedded/_layout/create-campaign'
      path: '/create-campaign'
      fullPath: '/embedded/create-campaign'
      preLoaderRoute: typeof EmbeddedLayoutCreateCampaignRouteImport
      parentRoute: typeof EmbeddedLayoutRoute
    }
    '/_restricted/push/create': {
      id: '/_restricted/push/create'
      path: '/push/create'
      fullPath: '/push/create'
      preLoaderRoute: typeof RestrictedPushCreateRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/push/confirm': {
      id: '/_restricted/push/confirm'
      path: '/push/confirm'
      fullPath: '/push/confirm'
      preLoaderRoute: typeof RestrictedPushConfirmRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/validation': {
      id: '/_restricted/campaigns/validation'
      path: '/campaigns/validation'
      fullPath: '/campaigns/validation'
      preLoaderRoute: typeof RestrictedCampaignsValidationRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/performance': {
      id: '/_restricted/campaigns/performance'
      path: '/campaigns/performance'
      fullPath: '/campaigns/performance'
      preLoaderRoute: typeof RestrictedCampaignsPerformanceRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/new': {
      id: '/_restricted/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof RestrictedCampaignsNewRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/metrics': {
      id: '/_restricted/campaigns/metrics'
      path: '/campaigns/metrics'
      fullPath: '/campaigns/metrics'
      preLoaderRoute: typeof RestrictedCampaignsMetricsRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/list': {
      id: '/_restricted/campaigns/list'
      path: '/campaigns/list'
      fullPath: '/campaigns/list'
      preLoaderRoute: typeof RestrictedCampaignsListRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/$campaignId': {
      id: '/_restricted/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof RestrictedCampaignsCampaignIdRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/product/$id/': {
      id: '/_restricted/product/$id/'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof RestrictedProductIdIndexRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/product/$id/team': {
      id: '/_restricted/product/$id/team'
      path: '/product/$id/team'
      fullPath: '/product/$id/team'
      preLoaderRoute: typeof RestrictedProductIdTeamRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/product/$id/setup-status': {
      id: '/_restricted/product/$id/setup-status'
      path: '/product/$id/setup-status'
      fullPath: '/product/$id/setup-status'
      preLoaderRoute: typeof RestrictedProductIdSetupStatusRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/product/$id/funding': {
      id: '/_restricted/product/$id/funding'
      path: '/product/$id/funding'
      fullPath: '/product/$id/funding'
      preLoaderRoute: typeof RestrictedProductIdFundingRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/edit/$campaignId': {
      id: '/_restricted/campaigns/edit/$campaignId'
      path: '/campaigns/edit/$campaignId'
      fullPath: '/campaigns/edit/$campaignId'
      preLoaderRoute: typeof RestrictedCampaignsEditCampaignIdRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/draft/$campaignId': {
      id: '/_restricted/campaigns/draft/$campaignId'
      path: '/campaigns/draft/$campaignId'
      fullPath: '/campaigns/draft/$campaignId'
      preLoaderRoute: typeof RestrictedCampaignsDraftCampaignIdRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/draft/$campaignId/validation': {
      id: '/_restricted/campaigns/draft/$campaignId/validation'
      path: '/validation'
      fullPath: '/campaigns/draft/$campaignId/validation'
      preLoaderRoute: typeof RestrictedCampaignsDraftCampaignIdValidationRouteImport
      parentRoute: typeof RestrictedCampaignsDraftCampaignIdRoute
    }
    '/_restricted/campaigns/draft/$campaignId/metrics': {
      id: '/_restricted/campaigns/draft/$campaignId/metrics'
      path: '/metrics'
      fullPath: '/campaigns/draft/$campaignId/metrics'
      preLoaderRoute: typeof RestrictedCampaignsDraftCampaignIdMetricsRouteImport
      parentRoute: typeof RestrictedCampaignsDraftCampaignIdRoute
    }
  }
}

interface RestrictedCampaignsDraftCampaignIdRouteChildren {
  RestrictedCampaignsDraftCampaignIdMetricsRoute: typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  RestrictedCampaignsDraftCampaignIdValidationRoute: typeof RestrictedCampaignsDraftCampaignIdValidationRoute
}

const RestrictedCampaignsDraftCampaignIdRouteChildren: RestrictedCampaignsDraftCampaignIdRouteChildren =
  {
    RestrictedCampaignsDraftCampaignIdMetricsRoute:
      RestrictedCampaignsDraftCampaignIdMetricsRoute,
    RestrictedCampaignsDraftCampaignIdValidationRoute:
      RestrictedCampaignsDraftCampaignIdValidationRoute,
  }

const RestrictedCampaignsDraftCampaignIdRouteWithChildren =
  RestrictedCampaignsDraftCampaignIdRoute._addFileChildren(
    RestrictedCampaignsDraftCampaignIdRouteChildren,
  )

interface RestrictedRouteChildren {
  RestrictedDashboardRoute: typeof RestrictedDashboardRoute
  RestrictedMembersRoute: typeof RestrictedMembersRoute
  RestrictedMintRoute: typeof RestrictedMintRoute
  RestrictedSettingsRoute: typeof RestrictedSettingsRoute
  RestrictedCampaignsCampaignIdRoute: typeof RestrictedCampaignsCampaignIdRoute
  RestrictedCampaignsListRoute: typeof RestrictedCampaignsListRoute
  RestrictedCampaignsMetricsRoute: typeof RestrictedCampaignsMetricsRoute
  RestrictedCampaignsNewRoute: typeof RestrictedCampaignsNewRoute
  RestrictedCampaignsPerformanceRoute: typeof RestrictedCampaignsPerformanceRoute
  RestrictedCampaignsValidationRoute: typeof RestrictedCampaignsValidationRoute
  RestrictedPushConfirmRoute: typeof RestrictedPushConfirmRoute
  RestrictedPushCreateRoute: typeof RestrictedPushCreateRoute
  RestrictedCampaignsDraftCampaignIdRoute: typeof RestrictedCampaignsDraftCampaignIdRouteWithChildren
  RestrictedCampaignsEditCampaignIdRoute: typeof RestrictedCampaignsEditCampaignIdRoute
  RestrictedProductIdFundingRoute: typeof RestrictedProductIdFundingRoute
  RestrictedProductIdSetupStatusRoute: typeof RestrictedProductIdSetupStatusRoute
  RestrictedProductIdTeamRoute: typeof RestrictedProductIdTeamRoute
  RestrictedProductIdIndexRoute: typeof RestrictedProductIdIndexRoute
}

const RestrictedRouteChildren: RestrictedRouteChildren = {
  RestrictedDashboardRoute: RestrictedDashboardRoute,
  RestrictedMembersRoute: RestrictedMembersRoute,
  RestrictedMintRoute: RestrictedMintRoute,
  RestrictedSettingsRoute: RestrictedSettingsRoute,
  RestrictedCampaignsCampaignIdRoute: RestrictedCampaignsCampaignIdRoute,
  RestrictedCampaignsListRoute: RestrictedCampaignsListRoute,
  RestrictedCampaignsMetricsRoute: RestrictedCampaignsMetricsRoute,
  RestrictedCampaignsNewRoute: RestrictedCampaignsNewRoute,
  RestrictedCampaignsPerformanceRoute: RestrictedCampaignsPerformanceRoute,
  RestrictedCampaignsValidationRoute: RestrictedCampaignsValidationRoute,
  RestrictedPushConfirmRoute: RestrictedPushConfirmRoute,
  RestrictedPushCreateRoute: RestrictedPushCreateRoute,
  RestrictedCampaignsDraftCampaignIdRoute:
    RestrictedCampaignsDraftCampaignIdRouteWithChildren,
  RestrictedCampaignsEditCampaignIdRoute:
    RestrictedCampaignsEditCampaignIdRoute,
  RestrictedProductIdFundingRoute: RestrictedProductIdFundingRoute,
  RestrictedProductIdSetupStatusRoute: RestrictedProductIdSetupStatusRoute,
  RestrictedProductIdTeamRoute: RestrictedProductIdTeamRoute,
  RestrictedProductIdIndexRoute: RestrictedProductIdIndexRoute,
}

const RestrictedRouteWithChildren = RestrictedRoute._addFileChildren(
  RestrictedRouteChildren,
)

interface EmbeddedLayoutRouteChildren {
  EmbeddedLayoutCreateCampaignRoute: typeof EmbeddedLayoutCreateCampaignRoute
  EmbeddedLayoutMintRoute: typeof EmbeddedLayoutMintRoute
  EmbeddedLayoutPurchaseTrackerRoute: typeof EmbeddedLayoutPurchaseTrackerRoute
}

const EmbeddedLayoutRouteChildren: EmbeddedLayoutRouteChildren = {
  EmbeddedLayoutCreateCampaignRoute: EmbeddedLayoutCreateCampaignRoute,
  EmbeddedLayoutMintRoute: EmbeddedLayoutMintRoute,
  EmbeddedLayoutPurchaseTrackerRoute: EmbeddedLayoutPurchaseTrackerRoute,
}

const EmbeddedLayoutRouteWithChildren = EmbeddedLayoutRoute._addFileChildren(
  EmbeddedLayoutRouteChildren,
)

interface EmbeddedRouteChildren {
  EmbeddedLayoutRoute: typeof EmbeddedLayoutRouteWithChildren
}

const EmbeddedRouteChildren: EmbeddedRouteChildren = {
  EmbeddedLayoutRoute: EmbeddedLayoutRouteWithChildren,
}

const EmbeddedRouteWithChildren = EmbeddedRoute._addFileChildren(
  EmbeddedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestrictedRoute: RestrictedRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  EmbeddedRoute: EmbeddedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
