/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as RestrictedRouteImport } from './routes/_restricted'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbeddedAuthRouteImport } from './routes/embedded/auth'
import { Route as EmbeddedLayoutRouteImport } from './routes/embedded/_layout'
import { Route as RestrictedSettingsRouteImport } from './routes/_restricted/settings'
import { Route as RestrictedMintRouteImport } from './routes/_restricted/mint'
import { Route as RestrictedMembersRouteImport } from './routes/_restricted/members'
import { Route as RestrictedDashboardRouteImport } from './routes/_restricted/dashboard'
import { Route as EmbeddedLayoutMintRouteImport } from './routes/embedded/_layout/mint'
import { Route as RestrictedPushCreateRouteImport } from './routes/_restricted/push/create'
import { Route as RestrictedPushConfirmRouteImport } from './routes/_restricted/push/confirm'
import { Route as RestrictedCampaignsPerformanceRouteImport } from './routes/_restricted/campaigns/performance'
import { Route as RestrictedCampaignsListRouteImport } from './routes/_restricted/campaigns/list'
import { Route as RestrictedCampaignsCampaignIdRouteImport } from './routes/_restricted/campaigns/$campaignId'
import { Route as RestrictedMerchantIdIndexRouteImport } from './routes/_restricted/merchant/$id/index'
import { Route as RestrictedMerchantIdTeamRouteImport } from './routes/_restricted/merchant/$id/team'
import { Route as RestrictedMerchantIdSetupStatusRouteImport } from './routes/_restricted/merchant/$id/setup-status'
import { Route as RestrictedMerchantIdFundingRouteImport } from './routes/_restricted/merchant/$id/funding'
import { Route as RestrictedCampaignsEditCampaignIdRouteImport } from './routes/_restricted/campaigns/edit/$campaignId'
import { Route as RestrictedCampaignsDraftNewRouteImport } from './routes/_restricted/campaigns/draft/new'
import { Route as RestrictedCampaignsDraftCampaignIdIndexRouteImport } from './routes/_restricted/campaigns/draft/$campaignId/index'
import { Route as RestrictedCampaignsDraftCampaignIdValidationRouteImport } from './routes/_restricted/campaigns/draft/$campaignId/validation'
import { Route as RestrictedCampaignsDraftCampaignIdMetricsRouteImport } from './routes/_restricted/campaigns/draft/$campaignId/metrics'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const RestrictedRoute = RestrictedRouteImport.update({
  id: '/_restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddedAuthRoute = EmbeddedAuthRouteImport.update({
  id: '/embedded/auth',
  path: '/embedded/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddedLayoutRoute = EmbeddedLayoutRouteImport.update({
  id: '/embedded/_layout',
  path: '/embedded',
  getParentRoute: () => rootRouteImport,
} as any)
const RestrictedSettingsRoute = RestrictedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedMintRoute = RestrictedMintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedMembersRoute = RestrictedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedDashboardRoute = RestrictedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RestrictedRoute,
} as any)
const EmbeddedLayoutMintRoute = EmbeddedLayoutMintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => EmbeddedLayoutRoute,
} as any)
const RestrictedPushCreateRoute = RestrictedPushCreateRouteImport.update({
  id: '/push/create',
  path: '/push/create',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedPushConfirmRoute = RestrictedPushConfirmRouteImport.update({
  id: '/push/confirm',
  path: '/push/confirm',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedCampaignsPerformanceRoute =
  RestrictedCampaignsPerformanceRouteImport.update({
    id: '/campaigns/performance',
    path: '/campaigns/performance',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsListRoute = RestrictedCampaignsListRouteImport.update({
  id: '/campaigns/list',
  path: '/campaigns/list',
  getParentRoute: () => RestrictedRoute,
} as any)
const RestrictedCampaignsCampaignIdRoute =
  RestrictedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMerchantIdIndexRoute =
  RestrictedMerchantIdIndexRouteImport.update({
    id: '/merchant/$id/',
    path: '/merchant/$id/',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMerchantIdTeamRoute =
  RestrictedMerchantIdTeamRouteImport.update({
    id: '/merchant/$id/team',
    path: '/merchant/$id/team',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMerchantIdSetupStatusRoute =
  RestrictedMerchantIdSetupStatusRouteImport.update({
    id: '/merchant/$id/setup-status',
    path: '/merchant/$id/setup-status',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedMerchantIdFundingRoute =
  RestrictedMerchantIdFundingRouteImport.update({
    id: '/merchant/$id/funding',
    path: '/merchant/$id/funding',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsEditCampaignIdRoute =
  RestrictedCampaignsEditCampaignIdRouteImport.update({
    id: '/campaigns/edit/$campaignId',
    path: '/campaigns/edit/$campaignId',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsDraftNewRoute =
  RestrictedCampaignsDraftNewRouteImport.update({
    id: '/campaigns/draft/new',
    path: '/campaigns/draft/new',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsDraftCampaignIdIndexRoute =
  RestrictedCampaignsDraftCampaignIdIndexRouteImport.update({
    id: '/campaigns/draft/$campaignId/',
    path: '/campaigns/draft/$campaignId/',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsDraftCampaignIdValidationRoute =
  RestrictedCampaignsDraftCampaignIdValidationRouteImport.update({
    id: '/campaigns/draft/$campaignId/validation',
    path: '/campaigns/draft/$campaignId/validation',
    getParentRoute: () => RestrictedRoute,
  } as any)
const RestrictedCampaignsDraftCampaignIdMetricsRoute =
  RestrictedCampaignsDraftCampaignIdMetricsRouteImport.update({
    id: '/campaigns/draft/$campaignId/metrics',
    path: '/campaigns/draft/$campaignId/metrics',
    getParentRoute: () => RestrictedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/dashboard': typeof RestrictedDashboardRoute
  '/members': typeof RestrictedMembersRoute
  '/mint': typeof RestrictedMintRoute
  '/settings': typeof RestrictedSettingsRoute
  '/embedded': typeof EmbeddedLayoutRouteWithChildren
  '/embedded/auth': typeof EmbeddedAuthRoute
  '/campaigns/$campaignId': typeof RestrictedCampaignsCampaignIdRoute
  '/campaigns/list': typeof RestrictedCampaignsListRoute
  '/campaigns/performance': typeof RestrictedCampaignsPerformanceRoute
  '/push/confirm': typeof RestrictedPushConfirmRoute
  '/push/create': typeof RestrictedPushCreateRoute
  '/embedded/mint': typeof EmbeddedLayoutMintRoute
  '/campaigns/draft/new': typeof RestrictedCampaignsDraftNewRoute
  '/campaigns/edit/$campaignId': typeof RestrictedCampaignsEditCampaignIdRoute
  '/merchant/$id/funding': typeof RestrictedMerchantIdFundingRoute
  '/merchant/$id/setup-status': typeof RestrictedMerchantIdSetupStatusRoute
  '/merchant/$id/team': typeof RestrictedMerchantIdTeamRoute
  '/merchant/$id/': typeof RestrictedMerchantIdIndexRoute
  '/campaigns/draft/$campaignId/metrics': typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  '/campaigns/draft/$campaignId/validation': typeof RestrictedCampaignsDraftCampaignIdValidationRoute
  '/campaigns/draft/$campaignId/': typeof RestrictedCampaignsDraftCampaignIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/dashboard': typeof RestrictedDashboardRoute
  '/members': typeof RestrictedMembersRoute
  '/mint': typeof RestrictedMintRoute
  '/settings': typeof RestrictedSettingsRoute
  '/embedded': typeof EmbeddedLayoutRouteWithChildren
  '/embedded/auth': typeof EmbeddedAuthRoute
  '/campaigns/$campaignId': typeof RestrictedCampaignsCampaignIdRoute
  '/campaigns/list': typeof RestrictedCampaignsListRoute
  '/campaigns/performance': typeof RestrictedCampaignsPerformanceRoute
  '/push/confirm': typeof RestrictedPushConfirmRoute
  '/push/create': typeof RestrictedPushCreateRoute
  '/embedded/mint': typeof EmbeddedLayoutMintRoute
  '/campaigns/draft/new': typeof RestrictedCampaignsDraftNewRoute
  '/campaigns/edit/$campaignId': typeof RestrictedCampaignsEditCampaignIdRoute
  '/merchant/$id/funding': typeof RestrictedMerchantIdFundingRoute
  '/merchant/$id/setup-status': typeof RestrictedMerchantIdSetupStatusRoute
  '/merchant/$id/team': typeof RestrictedMerchantIdTeamRoute
  '/merchant/$id': typeof RestrictedMerchantIdIndexRoute
  '/campaigns/draft/$campaignId/metrics': typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  '/campaigns/draft/$campaignId/validation': typeof RestrictedCampaignsDraftCampaignIdValidationRoute
  '/campaigns/draft/$campaignId': typeof RestrictedCampaignsDraftCampaignIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_restricted': typeof RestrictedRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/_restricted/dashboard': typeof RestrictedDashboardRoute
  '/_restricted/members': typeof RestrictedMembersRoute
  '/_restricted/mint': typeof RestrictedMintRoute
  '/_restricted/settings': typeof RestrictedSettingsRoute
  '/embedded/_layout': typeof EmbeddedLayoutRouteWithChildren
  '/embedded/auth': typeof EmbeddedAuthRoute
  '/_restricted/campaigns/$campaignId': typeof RestrictedCampaignsCampaignIdRoute
  '/_restricted/campaigns/list': typeof RestrictedCampaignsListRoute
  '/_restricted/campaigns/performance': typeof RestrictedCampaignsPerformanceRoute
  '/_restricted/push/confirm': typeof RestrictedPushConfirmRoute
  '/_restricted/push/create': typeof RestrictedPushCreateRoute
  '/embedded/_layout/mint': typeof EmbeddedLayoutMintRoute
  '/_restricted/campaigns/draft/new': typeof RestrictedCampaignsDraftNewRoute
  '/_restricted/campaigns/edit/$campaignId': typeof RestrictedCampaignsEditCampaignIdRoute
  '/_restricted/merchant/$id/funding': typeof RestrictedMerchantIdFundingRoute
  '/_restricted/merchant/$id/setup-status': typeof RestrictedMerchantIdSetupStatusRoute
  '/_restricted/merchant/$id/team': typeof RestrictedMerchantIdTeamRoute
  '/_restricted/merchant/$id/': typeof RestrictedMerchantIdIndexRoute
  '/_restricted/campaigns/draft/$campaignId/metrics': typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  '/_restricted/campaigns/draft/$campaignId/validation': typeof RestrictedCampaignsDraftCampaignIdValidationRoute
  '/_restricted/campaigns/draft/$campaignId/': typeof RestrictedCampaignsDraftCampaignIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/not-found'
    | '/dashboard'
    | '/members'
    | '/mint'
    | '/settings'
    | '/embedded'
    | '/embedded/auth'
    | '/campaigns/$campaignId'
    | '/campaigns/list'
    | '/campaigns/performance'
    | '/push/confirm'
    | '/push/create'
    | '/embedded/mint'
    | '/campaigns/draft/new'
    | '/campaigns/edit/$campaignId'
    | '/merchant/$id/funding'
    | '/merchant/$id/setup-status'
    | '/merchant/$id/team'
    | '/merchant/$id/'
    | '/campaigns/draft/$campaignId/metrics'
    | '/campaigns/draft/$campaignId/validation'
    | '/campaigns/draft/$campaignId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/not-found'
    | '/dashboard'
    | '/members'
    | '/mint'
    | '/settings'
    | '/embedded'
    | '/embedded/auth'
    | '/campaigns/$campaignId'
    | '/campaigns/list'
    | '/campaigns/performance'
    | '/push/confirm'
    | '/push/create'
    | '/embedded/mint'
    | '/campaigns/draft/new'
    | '/campaigns/edit/$campaignId'
    | '/merchant/$id/funding'
    | '/merchant/$id/setup-status'
    | '/merchant/$id/team'
    | '/merchant/$id'
    | '/campaigns/draft/$campaignId/metrics'
    | '/campaigns/draft/$campaignId/validation'
    | '/campaigns/draft/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/_restricted'
    | '/demo'
    | '/login'
    | '/not-found'
    | '/_restricted/dashboard'
    | '/_restricted/members'
    | '/_restricted/mint'
    | '/_restricted/settings'
    | '/embedded/_layout'
    | '/embedded/auth'
    | '/_restricted/campaigns/$campaignId'
    | '/_restricted/campaigns/list'
    | '/_restricted/campaigns/performance'
    | '/_restricted/push/confirm'
    | '/_restricted/push/create'
    | '/embedded/_layout/mint'
    | '/_restricted/campaigns/draft/new'
    | '/_restricted/campaigns/edit/$campaignId'
    | '/_restricted/merchant/$id/funding'
    | '/_restricted/merchant/$id/setup-status'
    | '/_restricted/merchant/$id/team'
    | '/_restricted/merchant/$id/'
    | '/_restricted/campaigns/draft/$campaignId/metrics'
    | '/_restricted/campaigns/draft/$campaignId/validation'
    | '/_restricted/campaigns/draft/$campaignId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestrictedRoute: typeof RestrictedRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  EmbeddedLayoutRoute: typeof EmbeddedLayoutRouteWithChildren
  EmbeddedAuthRoute: typeof EmbeddedAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_restricted': {
      id: '/_restricted'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embedded/auth': {
      id: '/embedded/auth'
      path: '/embedded/auth'
      fullPath: '/embedded/auth'
      preLoaderRoute: typeof EmbeddedAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embedded/_layout': {
      id: '/embedded/_layout'
      path: '/embedded'
      fullPath: '/embedded'
      preLoaderRoute: typeof EmbeddedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_restricted/settings': {
      id: '/_restricted/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof RestrictedSettingsRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/mint': {
      id: '/_restricted/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof RestrictedMintRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/members': {
      id: '/_restricted/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof RestrictedMembersRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/dashboard': {
      id: '/_restricted/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof RestrictedDashboardRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/embedded/_layout/mint': {
      id: '/embedded/_layout/mint'
      path: '/mint'
      fullPath: '/embedded/mint'
      preLoaderRoute: typeof EmbeddedLayoutMintRouteImport
      parentRoute: typeof EmbeddedLayoutRoute
    }
    '/_restricted/push/create': {
      id: '/_restricted/push/create'
      path: '/push/create'
      fullPath: '/push/create'
      preLoaderRoute: typeof RestrictedPushCreateRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/push/confirm': {
      id: '/_restricted/push/confirm'
      path: '/push/confirm'
      fullPath: '/push/confirm'
      preLoaderRoute: typeof RestrictedPushConfirmRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/performance': {
      id: '/_restricted/campaigns/performance'
      path: '/campaigns/performance'
      fullPath: '/campaigns/performance'
      preLoaderRoute: typeof RestrictedCampaignsPerformanceRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/list': {
      id: '/_restricted/campaigns/list'
      path: '/campaigns/list'
      fullPath: '/campaigns/list'
      preLoaderRoute: typeof RestrictedCampaignsListRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/$campaignId': {
      id: '/_restricted/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof RestrictedCampaignsCampaignIdRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/merchant/$id/': {
      id: '/_restricted/merchant/$id/'
      path: '/merchant/$id'
      fullPath: '/merchant/$id/'
      preLoaderRoute: typeof RestrictedMerchantIdIndexRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/merchant/$id/team': {
      id: '/_restricted/merchant/$id/team'
      path: '/merchant/$id/team'
      fullPath: '/merchant/$id/team'
      preLoaderRoute: typeof RestrictedMerchantIdTeamRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/merchant/$id/setup-status': {
      id: '/_restricted/merchant/$id/setup-status'
      path: '/merchant/$id/setup-status'
      fullPath: '/merchant/$id/setup-status'
      preLoaderRoute: typeof RestrictedMerchantIdSetupStatusRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/merchant/$id/funding': {
      id: '/_restricted/merchant/$id/funding'
      path: '/merchant/$id/funding'
      fullPath: '/merchant/$id/funding'
      preLoaderRoute: typeof RestrictedMerchantIdFundingRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/edit/$campaignId': {
      id: '/_restricted/campaigns/edit/$campaignId'
      path: '/campaigns/edit/$campaignId'
      fullPath: '/campaigns/edit/$campaignId'
      preLoaderRoute: typeof RestrictedCampaignsEditCampaignIdRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/draft/new': {
      id: '/_restricted/campaigns/draft/new'
      path: '/campaigns/draft/new'
      fullPath: '/campaigns/draft/new'
      preLoaderRoute: typeof RestrictedCampaignsDraftNewRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/draft/$campaignId/': {
      id: '/_restricted/campaigns/draft/$campaignId/'
      path: '/campaigns/draft/$campaignId'
      fullPath: '/campaigns/draft/$campaignId/'
      preLoaderRoute: typeof RestrictedCampaignsDraftCampaignIdIndexRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/draft/$campaignId/validation': {
      id: '/_restricted/campaigns/draft/$campaignId/validation'
      path: '/campaigns/draft/$campaignId/validation'
      fullPath: '/campaigns/draft/$campaignId/validation'
      preLoaderRoute: typeof RestrictedCampaignsDraftCampaignIdValidationRouteImport
      parentRoute: typeof RestrictedRoute
    }
    '/_restricted/campaigns/draft/$campaignId/metrics': {
      id: '/_restricted/campaigns/draft/$campaignId/metrics'
      path: '/campaigns/draft/$campaignId/metrics'
      fullPath: '/campaigns/draft/$campaignId/metrics'
      preLoaderRoute: typeof RestrictedCampaignsDraftCampaignIdMetricsRouteImport
      parentRoute: typeof RestrictedRoute
    }
  }
}

interface RestrictedRouteChildren {
  RestrictedDashboardRoute: typeof RestrictedDashboardRoute
  RestrictedMembersRoute: typeof RestrictedMembersRoute
  RestrictedMintRoute: typeof RestrictedMintRoute
  RestrictedSettingsRoute: typeof RestrictedSettingsRoute
  RestrictedCampaignsCampaignIdRoute: typeof RestrictedCampaignsCampaignIdRoute
  RestrictedCampaignsListRoute: typeof RestrictedCampaignsListRoute
  RestrictedCampaignsPerformanceRoute: typeof RestrictedCampaignsPerformanceRoute
  RestrictedPushConfirmRoute: typeof RestrictedPushConfirmRoute
  RestrictedPushCreateRoute: typeof RestrictedPushCreateRoute
  RestrictedCampaignsDraftNewRoute: typeof RestrictedCampaignsDraftNewRoute
  RestrictedCampaignsEditCampaignIdRoute: typeof RestrictedCampaignsEditCampaignIdRoute
  RestrictedMerchantIdFundingRoute: typeof RestrictedMerchantIdFundingRoute
  RestrictedMerchantIdSetupStatusRoute: typeof RestrictedMerchantIdSetupStatusRoute
  RestrictedMerchantIdTeamRoute: typeof RestrictedMerchantIdTeamRoute
  RestrictedMerchantIdIndexRoute: typeof RestrictedMerchantIdIndexRoute
  RestrictedCampaignsDraftCampaignIdMetricsRoute: typeof RestrictedCampaignsDraftCampaignIdMetricsRoute
  RestrictedCampaignsDraftCampaignIdValidationRoute: typeof RestrictedCampaignsDraftCampaignIdValidationRoute
  RestrictedCampaignsDraftCampaignIdIndexRoute: typeof RestrictedCampaignsDraftCampaignIdIndexRoute
}

const RestrictedRouteChildren: RestrictedRouteChildren = {
  RestrictedDashboardRoute: RestrictedDashboardRoute,
  RestrictedMembersRoute: RestrictedMembersRoute,
  RestrictedMintRoute: RestrictedMintRoute,
  RestrictedSettingsRoute: RestrictedSettingsRoute,
  RestrictedCampaignsCampaignIdRoute: RestrictedCampaignsCampaignIdRoute,
  RestrictedCampaignsListRoute: RestrictedCampaignsListRoute,
  RestrictedCampaignsPerformanceRoute: RestrictedCampaignsPerformanceRoute,
  RestrictedPushConfirmRoute: RestrictedPushConfirmRoute,
  RestrictedPushCreateRoute: RestrictedPushCreateRoute,
  RestrictedCampaignsDraftNewRoute: RestrictedCampaignsDraftNewRoute,
  RestrictedCampaignsEditCampaignIdRoute:
    RestrictedCampaignsEditCampaignIdRoute,
  RestrictedMerchantIdFundingRoute: RestrictedMerchantIdFundingRoute,
  RestrictedMerchantIdSetupStatusRoute: RestrictedMerchantIdSetupStatusRoute,
  RestrictedMerchantIdTeamRoute: RestrictedMerchantIdTeamRoute,
  RestrictedMerchantIdIndexRoute: RestrictedMerchantIdIndexRoute,
  RestrictedCampaignsDraftCampaignIdMetricsRoute:
    RestrictedCampaignsDraftCampaignIdMetricsRoute,
  RestrictedCampaignsDraftCampaignIdValidationRoute:
    RestrictedCampaignsDraftCampaignIdValidationRoute,
  RestrictedCampaignsDraftCampaignIdIndexRoute:
    RestrictedCampaignsDraftCampaignIdIndexRoute,
}

const RestrictedRouteWithChildren = RestrictedRoute._addFileChildren(
  RestrictedRouteChildren,
)

interface EmbeddedLayoutRouteChildren {
  EmbeddedLayoutMintRoute: typeof EmbeddedLayoutMintRoute
}

const EmbeddedLayoutRouteChildren: EmbeddedLayoutRouteChildren = {
  EmbeddedLayoutMintRoute: EmbeddedLayoutMintRoute,
}

const EmbeddedLayoutRouteWithChildren = EmbeddedLayoutRoute._addFileChildren(
  EmbeddedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestrictedRoute: RestrictedRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  EmbeddedLayoutRoute: EmbeddedLayoutRouteWithChildren,
  EmbeddedAuthRoute: EmbeddedAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
