import Foundation
import Testing

@testable import FrakSDK

/// Pins the `products` query-parameter encoding against `sdk/core`'s `compressJsonToB64`
/// (`sdk/core/src/utils/compression/compress.ts`) — golden vectors generated by running that
/// function directly in `sdk/core`, not reimplemented here. A Kotlin/Swift/TS drift in this
/// encoding degrades reward selection silently on whichever side is wrong, so these are
/// exact-string assertions, not shape assertions.
@Suite("ProductDetailsQueryEncoder")
struct ProductDetailsQueryEncoderTests {
    private static let logger = FrakLogger(level: .none)

    @Test("a product with every scope field matches sdk/core's compressJsonToB64 byte for byte")
    func matchesGoldenVectorAllFields() {
        let product = ProductDetails(
            productId: "p1",
            sku: "SHOE-42",
            name: "Kettle",
            quantity: 2,
            unitPrice: 79.9,
            totalPrice: 159.8
        )

        let encoded = ProductDetailsQueryEncoder.encode([product], logger: Self.logger)

        #expect(
            encoded
                == "W3sibmFtZSI6IktldHRsZSIsInByb2R1Y3RJZCI6InAxIiwicXVhbnRpdHkiOjIsInNrdSI6IlNIT0UtNDIiLCJ0b3RhbFByaWNlIjoxNTkuOCwidW5pdFByaWNlIjo3OS45fV0"
        )
    }

    @Test("a sparse product (one field) matches sdk/core's golden vector")
    func matchesGoldenVectorSparse() {
        let encoded = ProductDetailsQueryEncoder.encode([ProductDetails(sku: "SHOE-42")], logger: Self.logger)

        #expect(encoded == "W3sic2t1IjoiU0hPRS00MiJ9XQ")
    }

    @Test("two products match sdk/core's golden vector")
    func matchesGoldenVectorTwoProducts() {
        let encoded = ProductDetailsQueryEncoder.encode(
            [ProductDetails(sku: "SHIRT-1"), ProductDetails(sku: "SHOE-42", name: "Sneakers")],
            logger: Self.logger
        )

        #expect(encoded == "W3sic2t1IjoiU0hJUlQtMSJ9LHsibmFtZSI6IlNuZWFrZXJzIiwic2t1IjoiU0hPRS00MiJ9XQ")
    }

    @Test("a non-ASCII name is emitted as raw UTF-8, matching sdk/core's golden vector")
    func matchesGoldenVectorNonASCII() {
        let encoded = ProductDetailsQueryEncoder.encode(
            [ProductDetails(name: "Babies camel cuir velours bout carr\u{00e9}")],
            logger: Self.logger
        )

        #expect(encoded == "W3sibmFtZSI6IkJhYmllcyBjYW1lbCBjdWlyIHZlbG91cnMgYm91dCBjYXJyw6kifV0")
    }

    @Test("an integral quantity encodes without a trailing .0")
    func integralQuantityHasNoTrailingZero() throws {
        let encoded = try #require(
            ProductDetailsQueryEncoder.encode([ProductDetails(quantity: 2)], logger: Self.logger)
        )

        let decoded = try #require(Base64URL.decode(encoded))
        let json = String(decoding: decoded, as: UTF8.self)
        #expect(json.contains("\"quantity\":2"))
        #expect(!json.contains("\"quantity\":2."))
    }

    @Test("null fields are omitted from the JSON, never emitted as null")
    func nullFieldsAreOmitted() throws {
        let encoded = try #require(
            ProductDetailsQueryEncoder.encode([ProductDetails(sku: "SHOE-42")], logger: Self.logger)
        )

        let decoded = try #require(Base64URL.decode(encoded))
        let json = String(decoding: decoded, as: UTF8.self)
        #expect(!json.contains("null"))
        #expect(json == #"[{"sku":"SHOE-42"}]"#)
    }

    @Test("an empty product list encodes to nil, not an empty array")
    func emptyListEncodesToNil() {
        #expect(ProductDetailsQueryEncoder.encode([], logger: Self.logger) == nil)
    }

    @Test("a list of entirely empty products encodes to nil")
    func allEmptyProductsEncodeToNil() {
        let encoded = ProductDetailsQueryEncoder.encode([ProductDetails(), ProductDetails()], logger: Self.logger)

        #expect(encoded == nil)
    }

    @Test("empty entries are dropped, non-empty ones survive")
    func emptyEntriesAreDroppedNonEmptySurvive() throws {
        let encoded = try #require(
            ProductDetailsQueryEncoder.encode([ProductDetails(), ProductDetails(sku: "SHOE-42")], logger: Self.logger)
        )

        let decoded = try #require(Base64URL.decode(encoded))
        #expect(String(decoding: decoded, as: UTF8.self) == #"[{"sku":"SHOE-42"}]"#)
    }

    @Test("a payload over the size budget is dropped rather than truncated, and warns")
    func oversizedPayloadIsDroppedAndWarns() {
        // Each product with an 8192-char sku alone blows the encoded budget several times over.
        let hugeProducts = (0..<50).map { ProductDetails(sku: String(repeating: "s", count: 8192), name: "p\($0)") }
        let sink = RecordingSink()
        let logger = FrakLogger(level: .warn, sink: sink)

        let encoded = ProductDetailsQueryEncoder.encode(hugeProducts, logger: logger)

        #expect(encoded == nil)
        #expect(sink.messages.contains { $0.contains("exceeds") })
    }

    @Test("a payload at or under the size budget is sent")
    func payloadUnderBudgetIsSent() {
        let product = ProductDetails(sku: "SHOE-42")
        let sink = RecordingSink()
        let logger = FrakLogger(level: .warn, sink: sink)

        let encoded = ProductDetailsQueryEncoder.encode([product], logger: logger)

        #expect(encoded != nil)
        #expect(sink.messages.isEmpty)
    }

    /// A hand-written fake, the way a merchant would write one — matching `FrakLogSink`'s own
    /// doc comment and the convention in `PublicSurfaceTests`.
    private final class RecordingSink: FrakLogSink, @unchecked Sendable {
        private let lock = NSLock()
        private var captured: [String] = []

        func log(level: FrakLogLevel, message: String, error: (any Error)?) {
            lock.lock()
            defer { lock.unlock() }
            captured.append(message)
        }

        var messages: [String] {
            lock.lock()
            defer { lock.unlock() }
            return captured
        }
    }
}

extension ProductDetailsQueryEncoderTests {
    /// NaN/Infinity have no JSON literal: `Double.description` writes `nan`/`inf`, which would
    /// make the payload unparseable and cost the whole basket its scope context. `JSON.stringify`
    /// writes `null` for these, which the backend's sanitizer discards — same outcome.
    @Test("a non-finite price is dropped rather than emitted as an invalid JSON token")
    func nonFiniteNumbersAreDropped() throws {
        let encoded = try #require(
            ProductDetailsQueryEncoder.encode(
                [ProductDetails(sku: "SHOE-42", quantity: .nan, unitPrice: .infinity)],
                logger: FrakLogger(level: .none)
            )
        )
        let json = try #require(Base64URL.decode(encoded).map { String(decoding: $0, as: UTF8.self) })

        #expect(json == #"[{"sku":"SHOE-42"}]"#)
    }

    /// A product whose only fields are non-finite has nothing left to say, so it drops out
    /// entirely rather than contributing `{}`.
    @Test("a product left empty by non-finite fields contributes no entry")
    func allNonFiniteContributesNothing() {
        #expect(
            ProductDetailsQueryEncoder.encode(
                [ProductDetails(quantity: .nan)],
                logger: FrakLogger(level: .none)
            ) == nil
        )
    }

    @Test("negative zero serializes the way JSON.stringify writes it")
    func negativeZeroMatchesJSONStringify() throws {
        let encoded = try #require(
            ProductDetailsQueryEncoder.encode(
                [ProductDetails(quantity: -0.0)],
                logger: FrakLogger(level: .none)
            )
        )
        let json = try #require(Base64URL.decode(encoded).map { String(decoding: $0, as: UTF8.self) })

        #expect(json == #"[{"quantity":0}]"#)
    }
}
