import type { Address, Hex } from "viem";

/**
 * Global open panel properties — kept intentionally small.
 *
 * Environment + session fields live here (propagated on every event).
 * Per-user attributes like `has_biometrics`, `install_source`, and `locale`
 * live on the OpenPanel **profile** (via `identify`) — see `globalProps.ts`.
 */
export type AnalyticsGlobalProperties = {
    // Identity
    wallet?: Address;
    // Environment (compile-time / once-per-session)
    isIframe: boolean;
    isPwa: boolean;
    isTauri?: boolean;
    platform?: "ios" | "android" | "web" | "unknown";
    // Pass a custom iframe referrer (since the event referrer could be overridden if user got multiple websites using frak open, see: https://github.com/Openpanel-dev/openpanel/issues/172)
    iframeReferrer?: string;
    // Embedded specifics
    productId?: Hex;
    contextUrl?: string;
    // Session / build
    session_id?: string;
    app_version?: string;
    /**
     * Persistent per-origin anonymous id generated by the SDK on the partner
     * site (localStorage). Propagated through the RPC handshake so listener
     * events can be joined with SDK events in OpenPanel funnels.
     */
    sdk_anonymous_id?: string;
};

/**
 * Different types of authentication events
 */
export type AnalyticsAuthenticationType =
    | "register"
    | "login"
    | "sso"
    | "pairing"
    | "demo";
