import type { Address } from "viem";

/**
 * Which build emitted the event. `wallet_standalone` is `sharing.html` /
 * `install.html`, which a native host opens as a full page load — the SPA
 * route renders the same views and is otherwise indistinguishable.
 */
export type AnalyticsSurface = "wallet" | "wallet_standalone" | "listener";

/**
 * Global open panel properties — kept intentionally small.
 *
 * Environment + session fields live here (propagated on every event).
 * Per-user attributes like `has_biometrics`, `install_source`, and `locale`
 * live on the OpenPanel **profile** (via `identify`) — see `globalProps.ts`.
 */
export type AnalyticsGlobalProperties = {
    // Identity
    wallet?: Address;
    // Environment (compile-time / once-per-session)
    surface: AnalyticsSurface;
    isIframe: boolean;
    isPwa: boolean;
    isTauri?: boolean;
    platform?: "ios" | "android" | "web" | "unknown";
    // Pass a custom iframe referrer (since the event referrer could be overridden if user got multiple websites using frak open, see: https://github.com/Openpanel-dev/openpanel/issues/172)
    iframeReferrer?: string;
    // Partner-site URL the iframe is resolving against
    contextUrl?: string;
    /**
     * Merchant the current surface is acting for. Global rather than per-event
     * so every modal, auth and onboarding event is attributable, and so a
     * funnel breakdown by merchant sees it on every step.
     */
    merchant_id?: string;
    // Session / build
    session_id?: string;
    app_version?: string;
    /**
     * Persistent per-origin anonymous id generated by the SDK on the partner
     * site (localStorage). Propagated through the RPC handshake so listener
     * events can be joined with SDK events in OpenPanel funnels.
     */
    sdk_anonymous_id?: string;
    /**
     * Overrides OpenPanel's own device derivation (project + IP + user agent,
     * rotated daily). Set from the same id as `sdk_anonymous_id` so a funnel
     * can span the partner page, the iframe and the wallet.
     */
    __deviceId?: string;
};
