#!/usr/bin/env bun
/**
 * Gates the tracked Android manifest against the prod deep-link config.
 *
 * The manifest is generated by `tauri-plugin-deep-link` but tracked, so a local
 * dev-config build rewrites it in place and the dev hosts are one `git commit -a`
 * from the release path. In a prod AAB they fail App Link verification outright:
 * `assetlinks.json` is stage-scoped, so nothing delegates to the prod package.
 */
import { readFileSync } from "node:fs";

const MANIFEST =
    "apps/wallet/src-tauri/gen/android/app/src/main/AndroidManifest.xml";
const PROD_CONFIG = "apps/wallet/src-tauri/tauri.conf.json";
const DEV_CONFIG = "apps/wallet/src-tauri/tauri.conf.android-dev.json";

type MobileEntry = { host?: string; scheme?: string[] };

function die(message: string): never {
    console.error(`❌ ${message}`);
    process.exit(1);
}

function read(file: string): string {
    try {
        return readFileSync(file, "utf8");
    } catch {
        return die(
            `${file} is unreadable — a deep-link site moved or was deleted.`
        );
    }
}

/** Hosts and custom schemes a config's `plugins.deep-link.mobile` declares. */
function declared(file: string): { hosts: string[]; schemes: string[] } {
    const config = JSON.parse(read(file));
    const mobile: MobileEntry[] = config?.plugins?.["deep-link"]?.mobile ?? [];
    if (mobile.length === 0) {
        die(
            `${file}: no plugins.deep-link.mobile entries — config changed shape.`
        );
    }
    const hosts = mobile.flatMap((e) => (e.host ? [e.host] : []));
    // `https` is the App Link transport, not a custom scheme; only the latter
    // distinguishes the variants.
    const schemes = mobile.flatMap((e) =>
        (e.scheme ?? []).filter((s) => s !== "https")
    );
    if (hosts.length === 0 || schemes.length === 0) {
        die(`${file}: expected at least one host and one custom scheme.`);
    }
    return { hosts, schemes };
}

const xml = read(MANIFEST);
const prod = declared(PROD_CONFIG);
const dev = declared(DEV_CONFIG);

// A dev overlay sharing any value with prod cannot scope a variant, and would
// also make every prod value read as a dev leak below. Caught here so the
// message names the overlay rather than blaming a correct manifest.
const shared = [
    ...prod.hosts.filter((h) => dev.hosts.includes(h)),
    ...prod.schemes.filter((s) => dev.schemes.includes(s)),
];
if (shared.length > 0) {
    die(
        `${DEV_CONFIG} shares deep-link values with prod: ${shared.join(", ")}\n` +
            "   The dev overlay exists to give each variant strict per-variant filters;\n" +
            "   one that does not override them lets a dev build claim the prod host."
    );
}

const hosts = [...xml.matchAll(/android:host="([^"]+)"/g)].map((m) => m[1]);
const schemes = [...xml.matchAll(/android:scheme="([^"]+)"/g)].map((m) => m[1]);

if (hosts.length === 0) {
    die(
        `${MANIFEST} declares no android:host.\n` +
            "   The deep-link filters are missing entirely — regenerate with a build."
    );
}

const leaked = [
    ...hosts.filter((h) => dev.hosts.includes(h)),
    ...schemes.filter((s) => dev.schemes.includes(s)),
];
if (leaked.length > 0) {
    die(
        `${MANIFEST} carries dev deep-link values: ${leaked.join(", ")}\n` +
            `   This is the output of a \`--config ${DEV_CONFIG}\` build. The tracked copy must\n` +
            "   stay on prod — restore it with:\n" +
            `     git checkout -- ${MANIFEST}`
    );
}

const missing = [
    ...prod.hosts.filter((h) => !hosts.includes(h)),
    ...prod.schemes.filter((s) => !schemes.includes(s)),
];
if (missing.length > 0) {
    die(
        `${MANIFEST} is missing prod deep-link values: ${missing.join(", ")}\n` +
            `   It has drifted behind ${PROD_CONFIG}; regenerate it with a prod-config build.`
    );
}

console.log(
    `✅ Android manifest on prod deep-links — ${prod.hosts.join(", ")} + ${prod.schemes
        .map((s) => `${s}://`)
        .join(", ")}`
);
