#!/usr/bin/env bun

function shellQuote(value: string): string {
    return `'${value.replace(/'/g, "'\\''")}'`;
}

const lines = Object.entries(process.env)
    .filter(([key]) => key.startsWith("TO_PRINT_"))
    .filter(([, value]) => value !== undefined)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
        ([key, value]) =>
            `${key.replace("TO_PRINT_", "")}=${shellQuote(value ?? "")}`
    );

const content = [
    "# Generated by: env:sandbox SST DevCommand",
    "# Re-run from SST dev UI to refresh. Do not commit this file.",
    "",
    ...lines,
    "",
].join("\n");

await Bun.write(".env.sandbox", content);

console.log(`.env.sandbox generated (${lines.length} variables)`);
