# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "87da8338f40c95301b4881ca4bfb23db"
application_url = "https://card-config-hub-volumes.trycloudflare.com"
embedded = true
name = "Frak"
handle = "frak"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events, write_pixels, read_pixels, read_themes, read_orders, read_products"

[auth]
redirect_urls = [
  "https://card-config-hub-volumes.trycloudflare.com/auth/callback",
  "https://card-config-hub-volumes.trycloudflare.com/auth/shopify/callback",
  "https://card-config-hub-volumes.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "paris-rooftop.myshopify.com"
automatically_update_urls_on_dev = true
