# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8bc45d423919a0074a2660d8d0feac5d"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "frak-app"
handle = "frak-app"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "paris-rooftop.myshopify.com"
