import type { LoaderFunctionArgs } from "@remix-run/node";
import { Form, redirect, useLoaderData } from "@remix-run/react";

import { login } from "../../shopify.server";

import styles from "./styles.module.css";

export const loader = async ({ request }: LoaderFunctionArgs) => {
    const url = new URL(request.url);

    if (url.searchParams.get("shop")) {
        throw redirect(`/app?${url.searchParams.toString()}`);
    }

    return Response.json({ showForm: Boolean(login) });
};

export default function App() {
    const { showForm } = useLoaderData<typeof loader>();

    return (
        <div className={styles.index}>
            <div className={styles.content}>
                <h1 className={styles.heading}>
                    Scale Authenticity with Word-of-Mouth
                </h1>
                <p className={styles.text}>
                    Reward your customers for genuine recommendations, cut
                    acquisition costs, and foster lasting loyalty.
                </p>
                {showForm && (
                    <Form
                        className={styles.form}
                        method="post"
                        action="/auth/login"
                    >
                        <label className={styles.label}>
                            <span>Shop domain</span>
                            <input
                                className={styles.input}
                                type="text"
                                name="shop"
                            />
                            <span>e.g: my-shop-domain.myshopify.com</span>
                        </label>
                        <button className={styles.button} type="submit">
                            Log in
                        </button>
                    </Form>
                )}
                <ul className={styles.list}>
                    <li>
                        <strong>Cash Rewards</strong>. Automatically and
                        instantly reward actions generated by sharing.
                    </li>
                    <li>
                        <strong>Return On Investment</strong>. Pay only for
                        results—your budget goes straight to your customers, not
                        social networks!
                    </li>
                    <li>
                        <strong>Lower Acquisition Costs</strong>. Reduce
                        acquisition costs up to 8.3 times compared to
                        traditional ads.
                    </li>
                    <li>
                        <strong>Increase Brand Loyalty</strong>. Create
                        authentic connections and boost loyalty by valuing every
                        customer.
                    </li>
                </ul>
            </div>
        </div>
    );
}
