/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly STAGE: string
  readonly BACKEND_URL: string
  readonly INDEXER_URL: string
  readonly ALCHEMY_API_KEY: string
  readonly PIMLICO_API_KEY: string
  readonly NEXUS_RPC_SECRET: string
  readonly VAPID_PUBLIC_KEY: string
  readonly UMAMI_WALLET_WEBSITE_ID: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}