import path from "node:path";

export type FrakStage = "prod" | "dev";

export type StageOrigins = {
    sdk: string;
    sdkFallbackTag: string;
    wallet: string;
    backend: string;
};

/**
 * The only place a storefront's origins are decided. `shopify app deploy`
 * uploads one build per app (FrakDev / Frak), so the stage is settled before
 * the files leave this repo — nothing resolves it at runtime.
 */
export const STAGE_ORIGINS: Record<FrakStage, StageOrigins> = {
    prod: {
        sdk: "https://sdk.frak.id",
        sdkFallbackTag: "latest",
        wallet: "https://wallet.frak.id",
        backend: "https://backend.frak.id",
    },
    dev: {
        sdk: "https://sdk-dev.frak.id",
        sdkFallbackTag: "beta",
        wallet: "https://wallet-dev.frak.id",
        backend: "https://backend.gcp-dev.frak.id",
    },
};

export const APP_ROOT = path.join(import.meta.dirname, "..");

export const LISTENER_PATH = path.join(
    APP_ROOT,
    "extensions/theme-components/blocks/listener.liquid"
);

export const STAGE_MODULE_PATH = path.join(
    APP_ROOT,
    "extensions/checkout-post-purchase/src/frakStage.gen.ts"
);

const REGION_BEGIN = "{% comment %} frak:stage:begin {% endcomment %}";
const REGION_END = "{% comment %} frak:stage:end {% endcomment %}";

export function renderLiquidRegion(origins: StageOrigins): string {
    return [
        REGION_BEGIN,
        "{% comment %}",
        "  Generated by scripts/generateStageArtifacts.ts. Edit that, not this:",
        "  `shopify app deploy` ships whatever sits here to every merchant of the",
        "  app it targets, and nothing downstream can tell a hand-edit from a build.",
        "{% endcomment %}",
        `{% assign frak_sdk_origin = '${origins.sdk}' %}`,
        `{% assign frak_sdk_fallback_tag = '${origins.sdkFallbackTag}' %}`,
        `{% assign frak_wallet_origin = '${origins.wallet}' %}`,
        `{% assign frak_backend_origin = '${origins.backend}' %}`,
        REGION_END,
    ].join("\n");
}

export function renderStageModule(origins: StageOrigins): string {
    return [
        "// Generated by scripts/generateStageArtifacts.ts — do not edit.",
        `export const FRAK_WALLET_ORIGIN = "${origins.wallet}";`,
        "",
    ].join("\n");
}

/**
 * Swap the generated region in place, so the block around it stays hand-written
 * and reviewable rather than becoming a template nobody reads.
 */
export function applyLiquidRegion(source: string, region: string): string {
    const begin = source.indexOf(REGION_BEGIN);
    const end = source.indexOf(REGION_END);
    if (begin === -1 || end === -1 || end < begin) {
        throw new Error(
            `listener.liquid lost its frak:stage markers — expected ${REGION_BEGIN} … ${REGION_END}`
        );
    }
    return (
        source.slice(0, begin) + region + source.slice(end + REGION_END.length)
    );
}
