name: 🚀 Deploy GCP

on:
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force the deployment (even if no file changes)'
        required: true
        type: boolean
        default: false
  push:
    branches:
      - dev

concurrency: ${{ github.workflow }}-${{ github.ref }}-gcp

env:
  CI: true

permissions:
  id-token: write
  contents: write

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deployment
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set commit hash for cache busting
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache SST
        id: sst-caching
        uses: actions/cache@v4
        with:
          path: | 
            .sst/platform/
            .sst/provider-lock.json
            .sst/esbuild.json
          key: ${{ runner.os }}-sst-${{ hashFiles('./sst.config.ts') }}
          restore-keys: ${{ runner.os }}-sst-

      - uses: dorny/paths-filter@v3
        name: Check changes
        id: changes
        with:
          base: ${{ github.ref }}
          list-files: 'shell'
          filters: |
            backend:
              - 'packages/backend-elysia/**'

      - name: Set up QEMU
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.force_deploy == 'true'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.force_deploy == 'true'
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: "🔨 Install dependencies"
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.force_deploy == 'true'
        run: bun install --frozen-lockfile

      - name: "🔨 Build the SDK"
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.force_deploy == 'true'
        run: bun run build:sdk

      - name: "👥 Configure AWS Credentials"
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.force_deploy == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::262732185023:role/github-action-deploy-role
          aws-region: eu-west-1
          retry-max-attempts: 5

      - name:  "👥 Login to Amazon ECR"
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.force_deploy == 'true'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: "👥 Login to Google Cloud"
        uses: 'google-github-actions/auth@v2'
        id: 'auth'
        with:
          workload_identity_provider: 'projects/426208135260/locations/global/workloadIdentityPools/github/providers/sst-deployer'
          service_account: 'sst-service-account@frak-main-v1.iam.gserviceaccount.com'
          project_id: 'frak-main-v1'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'frak-main-v1'
          install_components: 'kubectl,gke-gcloud-auth-plugin'

      - name: 'Docker and k8s Auth'
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          gcloud container clusters get-credentials master-cluster --location europe-west1-b --project frak-main-v1

      - name: "🔧 Setup environment"
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.force_deploy == 'true'
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "STAGE=gcp-production" >> $GITHUB_ENV
          else
            echo "STAGE=gcp-staging" >> $GITHUB_ENV
          fi

      - name: "🚀 SST Deploy"
        if: steps.changes.outputs.backend == 'true' || github.event.inputs.force_deploy == 'true'
        run: |
          STAGE=${STAGE_OVERRIDE:-$STAGE}
          echo "Deploying with stage: $STAGE"
          bun sst install
          bun sst deploy --stage $STAGE
        env:
          STAGE: ${{ env.STAGE }}
