name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:


concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: "🔨 Install dependencies"
        run: bun install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        id: changesets
        with:
          publish: bun publish
          version: bun changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: gacts/purge-jsdelivr-cache@v1
        if: steps.changesets.outputs.published == 'true'
        with:
          url: |
            https://cdn.jsdelivr.net/npm/@frak-labs/nexus-sdk@latest/dist/bundle/bundle.js
            https://cdn.jsdelivr.net/npm/@frak-labs/core-sdk@latest/dist/bundle/bundle.js
            https://cdn.jsdelivr.net/npm/@frak-labs/components@latest/dist/bundle/components.js